"""Build Windows capture helper/maintenance without executing either executable.

Produces an explicit NSIS overlay and fixed encoded bootstrap actions. All hashes
come from this build's files; no caller-controlled path or value reaches elevation.
"""
import argparse
import base64
import gzip
import hashlib
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[4]
DESKTOP = ROOT / 'crates/apps/rokbattles-desktop'
TARGETS = ('x86_64-pc-windows-msvc', 'aarch64-pc-windows-msvc')


def digest(path):
    return hashlib.file_digest(path.open('rb'), 'sha256').hexdigest()


def encode(source):
    # Keep total process command size bounded. Compress this exact compiled code,
    # never caller input, then run it entirely in the native OS PowerShell process.
    source = '\n'.join(line.strip() for line in source.splitlines() if not line.lstrip().startswith('#'))
    payload = base64.b64encode(gzip.compress(source.encode(), mtime=0)).decode('ascii')
    loader = "$b=[Convert]::FromBase64String('" + payload + "');$m=New-Object IO.MemoryStream(,$b);$g=New-Object IO.Compression.GZipStream($m,[IO.Compression.CompressionMode]::Decompress);$r=New-Object IO.StreamReader($g);& ([ScriptBlock]::Create($r.ReadToEnd()))"
    encoded = base64.b64encode(loader.encode('utf-16-le')).decode('ascii')
    # Worst-case NSIS system-path string, fixed switches, encoded payload and NUL.
    if 2 * (1024 + 200 + len(encoded) + 1) > 32768:
        raise ValueError('process command exceeds native UTF-16 allocation')
    if len(encoded) > 14000:
        raise ValueError('bootstrap exceeds bounded NSIS command size')
    return encoded


def generate(source, target):
    if target not in TARGETS:
        raise ValueError('unsupported maintenance target')
    destination = DESKTOP / 'binaries' / target
    destination.mkdir(parents=True, exist_ok=True)
    if destination.is_symlink() or destination.parent.is_symlink():
        raise ValueError('linked staging directory')
    pins = {}
    for name in ('rokbattles-capture-helper.exe', 'rokbattles-desktop-agent.exe', 'rokbattles-capture-maintenance.exe'):
        original = source / name
        if original.is_symlink() or not original.is_file():
            raise ValueError('missing native build output')
        data = original.read_bytes()
        if (destination / name).is_symlink():
            raise ValueError('linked staging file')
        (destination / name).write_bytes(data)
        pins[name.replace('maintenance.exe', 'maintenance.next.exe')] = hashlib.sha256(data).hexdigest()
    (destination / 'payload.json').write_text(json.dumps(pins, sort_keys=True) + '\n')
    source = (DESKTOP / 'windows/bootstrap.ps1').read_text()
    current = pins['rokbattles-capture-maintenance.next.exe']
    actions = {
        'ROOT': "Create-Protected $Root; Create-Protected $Maintenance",
        'INITIAL': f"Assert-Protected $Root; Assert-Protected $Maintenance; Verify-Pin $Image '{current}'; Write-AtomicPins @('{current}')",
        'EXISTING': "Assert-Protected $Root; Assert-Protected $Maintenance; [void](Find-CurrentPin)",
        'PREPROMOTE': f"Assert-Protected $Root; Assert-Protected $Maintenance; $Old=Find-CurrentPin; Verify-Pin (Join-Path $Maintenance 'rokbattles-capture-maintenance.next.exe') '{current}'; Write-AtomicPins @($Old, '{current}')",
        'FINAL': f"Assert-Protected $Root; Assert-Protected $Maintenance; Complete-Promotion '{current}'",
    }
    generated = '; Generated by stage_maintenance.py; never edit or invoke directly.\n'
    for name, action in actions.items():
        encoded = encode(source + chr(10) + action)
        generated += f'!macro ROK_APPEND_BOOTSTRAP_{name}\n'
        for offset in range(0, len(encoded), 512):
            chunk = encoded[offset:offset + 512]
            generated += f'  System::Call \'kernel32::lstrcpyW(p $RokCommandCursor, w "{chunk}")\'\n'
            generated += f'  IntOp $RokCommandCursor $RokCommandCursor + {len(chunk) * 2}\n'
        generated += '!macroend\n' 
    (destination / 'bootstrap.nsh').write_text(generated)
    # Explicit resources install all user-independent app binaries at the fixed
    # root. The maintenance binary itself is managed only by the gated hooks.
    overlay = {
        'bundle': {
            'externalBin': ['binaries/rokbattles-desktop-agent'],
            'resources': {f'binaries/{target}/rokbattles-capture-helper.exe': 'rokbattles-capture-helper.exe'},
            'windows': {'nsis': {'installMode': 'perMachine', 'installerHooks': f'windows/capture-{target}.nsh'}},
        }
    }
    (DESKTOP / f'tauri.capture-{target}.conf.json').write_text(json.dumps(overlay, indent=2) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--target', choices=TARGETS, required=True)
    parser.add_argument('--debug', action='store_true')
    args = parser.parse_args()
    command = ['cargo', 'build', '--locked', '--target', args.target]
    for name in ('rokbattles-capture-helper', 'rokbattles-capture-maintenance', 'rokbattles-desktop-agent'):
        command.extend(['-p', name])
    if not args.debug:
        command.append('--release')
    subprocess.run(command, cwd=ROOT, check=True)
    metadata = json.loads(subprocess.check_output(['cargo', 'metadata', '--no-deps', '--format-version', '1'], cwd=ROOT, text=True))
    generate(pathlib.Path(metadata['target_directory']) / args.target / ('debug' if args.debug else 'release'), args.target)


if __name__ == '__main__':
    main()
