[package]
name = "rokbattles-dns-resolver"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "query", "tokio"] }
base64 = { workspace = true }
dotenvy = { workspace = true }
hickory-proto = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
