[package]
name = "rokbattles-jobs"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dotenvy = { workspace = true }
rokbattles-drastc = { path = "../../common/rokbattles-drastc" }
futures = { workspace = true, features = ["std"] }
mongodb = { workspace = true }
rokbattles-api = { path = "../rokbattles-api" }
rokbattles-bson = { path = "../../common/rokbattles-bson" }
serde = { workspace = true, features = ["derive"] }
sentry = { workspace = true, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }
tokio-cron-scheduler = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
yaml_serde = { workspace = true }

[target.'cfg(all(target_os = "linux", target_env = "musl"))'.dependencies]
mimalloc = { workspace = true, features = ["secure"] }

[lib]
doctest = false
