[package]
name = "rokbattles-mail-decoder"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rokbattles-mail-decoder-simd = { path = "../rokbattles-mail-decoder-simd" }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lib]
doctest = false
