import commandersData from "@/autogenerated/commanders.json";
import { type DatasetLocale, defaultLocale, isDatasetLocale } from "@/i18n/config";

export const commanderMap = commandersData.commanders;

type CommanderIdKey = keyof typeof commanderMap;
type CommanderEntry = (typeof commanderMap)[CommanderIdKey];
type CommanderLocale = keyof CommanderEntry["name"];

export function resolveCommanderLocale(locale?: string): DatasetLocale {
  if (locale && isDatasetLocale(locale)) {
    return locale;
  }

  return defaultLocale;
}

export function getCommanderName(id: number | null | undefined, locale?: string) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander) {
    return undefined;
  }

  const resolvedLocale = resolveCommanderLocale(locale);
  return (
    (commander.name as Record<string, string | undefined>)[resolvedLocale] ??
    commander.name[defaultLocale as CommanderLocale]
  );
}
