import commandersData from "@/autogenerated/commanders.json";
import { defaultLocale, isLocale, type Locale } from "@/i18n/config";

export const commanderMap = commandersData.commanders;

type CommanderIdKey = keyof typeof commanderMap;
type CommanderEntry = (typeof commanderMap)[CommanderIdKey];
type CommanderLocale = keyof CommanderEntry["name"];

export function resolveCommanderLocale(locale?: string): Locale {
  if (locale && isLocale(locale)) {
    return locale;
  }

  return defaultLocale;
}

export function getCommanderName(id: number | null | undefined, locale?: string) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander) {
    return undefined;
  }

  const resolvedLocale = resolveCommanderLocale(locale);
  return (
    (commander.name as Record<string, string | undefined>)[resolvedLocale] ??
    commander.name[defaultLocale as CommanderLocale]
  );
}

export function getCommanderSprites(id: number | null | undefined): string[] | undefined {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander?.sprite) {
    return undefined;
  }

  const sprites = Array.isArray(commander.sprite) ? commander.sprite : [commander.sprite];

  return sprites
    .filter((sprite): sprite is string => typeof sprite === "string" && sprite.length > 0)
    .map((sprite) => `https://cdn.rokbattles.com/game/sprites/${sprite}`);
}
