import lootData from "@/autogenerated/loot.json";
import { defaultLocale, isLocale } from "@/i18n/config";

type LootCatalogEntry = {
  name: Record<string, string | undefined>;
};

type LootCatalog = Record<string, Record<string, LootCatalogEntry>>;

const lootCatalog = lootData.loot as LootCatalog;
const lootOrder = new Map<string, number>();
let lootOrderIndex = 0;

for (const [typeId, entries] of Object.entries(lootCatalog)) {
  for (const subTypeId of Object.keys(entries)) {
    lootOrder.set(`${typeId}:${subTypeId}`, lootOrderIndex);
    lootOrderIndex += 1;
  }
}

function resolveLocale(locale?: string): string {
  return isLocale(locale) ? locale : defaultLocale;
}

export function getLootName(
  typeId: number | null | undefined,
  subTypeId: number | null | undefined,
  locale?: string
): string | undefined {
  if (typeof typeId !== "number" || !Number.isFinite(typeId)) {
    return undefined;
  }

  if (typeof subTypeId !== "number" || !Number.isFinite(subTypeId)) {
    return undefined;
  }

  const typeEntry = lootCatalog[String(typeId)];
  if (!typeEntry) {
    return undefined;
  }

  const lootEntry = typeEntry[String(subTypeId)];
  if (!lootEntry) {
    return undefined;
  }

  const targetLocale = resolveLocale(locale);
  return lootEntry.name[targetLocale] ?? lootEntry.name[defaultLocale];
}

export function getLootOrder(
  typeId: number | null | undefined,
  subTypeId: number | null | undefined
): number | undefined {
  if (typeof typeId !== "number" || !Number.isFinite(typeId)) {
    return undefined;
  }

  if (typeof subTypeId !== "number" || !Number.isFinite(subTypeId)) {
    return undefined;
  }

  return lootOrder.get(`${typeId}:${subTypeId}`);
}
