import commandersData from "@/autogenerated/commanders.json";

type CommanderLocales = Record<string, string | undefined>;
interface CommanderEntry {
  name?: CommanderLocales;
}

const commanderMap = (
  commandersData as { commanders?: Record<string, CommanderEntry> }
).commanders;

function isCommanderId(id: number | null | undefined): id is number {
  return typeof id === "number" && Number.isFinite(id);
}

export function getCommanderName(
  id: number | null | undefined
): string | undefined {
  if (!isCommanderId(id)) {
    return undefined;
  }

  const commander = commanderMap?.[String(id)];
  if (!commander?.name) {
    return undefined;
  }

  return (
    commander.name.en ??
    Object.values(commander.name).find(
      (name): name is string => typeof name === "string" && name.length > 0
    )
  );
}

export function getCommanderNameOrId(
  id: number | null | undefined
): string | undefined {
  if (!isCommanderId(id)) {
    return undefined;
  }

  return getCommanderName(id) ?? String(id);
}
