[package]
name = "mail-cli"
version = "1.0.2"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
mail-decoder = { path = "../../crates/mail-decoder" }
mail-processor-alliance-aoobattleinfo = { path = "../../crates/mail-processor-alliance-aoobattleinfo" }
mail-processor-alliance-aoobattleresults = { path = "../../crates/mail-processor-alliance-aoobattleresults" }
mail-processor-alliance-aooindividualresults = { path = "../../crates/mail-processor-alliance-aooindividualresults" }
mail-processor-barcanyonkillboss = { path = "../../crates/mail-processor-barcanyonkillboss" }
mail-processor-battle = { path = "../../crates/mail-processor-battle" }
mail-processor-duelbattle2 = { path = "../../crates/mail-processor-duelbattle2" }
mail-processor-rss = { path = "../../crates/mail-processor-rss" }
mail-processor-system-barbarianfort = { path = "../../crates/mail-processor-system-barbarianfort" }
mail-processor-sdk = { path = "../../crates/mail-processor-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false
