[package]
name = "mail-cli"
version = "1.0.4"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
mail-decoder = { path = "../../crates/mail-decoder" }
mail-registry = { path = "../../crates/mail-registry", features = ["processors"] }
mail-processor-sdk = { path = "../../crates/mail-processor-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false
