packages:
  - crates/*
  - site
  - nxt
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
patchedDependencies:
  next-themes: patches/next-themes.patch
