packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true

overrides:
  postcss: 8.5.15

shellEmulator: true

minimumReleaseAge: 2880 # 48 hours
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - next
  - "@next/*"
