packages:
  - apps/*
  - site

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true

shellEmulator: true

minimumReleaseAge: 2880 # 48 hours
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude: []
