import resourcesData from "@/autogenerated/resources.json";
import { defaultLocale, isLocale } from "@/i18n/config";

type ResourceCatalogEntry = {
  name: Record<string, string | undefined>;
};

type ResourceCatalog = Record<string, ResourceCatalogEntry>;

const resourceCatalog = resourcesData.resources as ResourceCatalog;

export const RESOURCE_TYPE_IDS = [1, 2, 3, 4, 5] as const;

function resolveLocale(locale?: string) {
  return isLocale(locale) ? locale : defaultLocale;
}

export function getResourceName(typeId: number | null | undefined, locale?: string) {
  if (typeof typeId !== "number" || !Number.isFinite(typeId)) {
    return undefined;
  }

  const entry = resourceCatalog[String(typeId)];
  if (!entry) {
    return undefined;
  }

  const targetLocale = resolveLocale(locale);
  return entry.name[targetLocale] ?? entry.name[defaultLocale];
}
