// Generated by rokbattles-codegen. Do not edit.

export type AllianceAooBattleResults = {
  metadata: MailMetadata;
  alliances: Array<BattleAllianceResult>;
  body: AllianceBattleBody;
  participants: Array<AllianceBattleParticipant>;
  overview: AllianceBattleOverview;
};
export type AllianceBattleBody = {
  type: number;
  param: number | null;
  battle_type: string;
  win: boolean;
  alliance: AllianceId;
};
export type AllianceBattleOverview = {
  flag_score: ScoreCategory;
  building_score: ScoreCategory;
  be_killed_score: ScoreCategory;
  gather_score: ScoreCategory;
  healing_score: ScoreCategory;
  killed_score: ScoreCategory;
};
export type AllianceBattleParticipant = {
  player_name: string;
  individual_points: number;
  building_score: number;
  gather_score: number;
  kill_score: number;
  flag_score: number;
};
export type AllianceId = {
  id: number;
};
export type BattleAlliance = {
  abbreviation: string | null;
  id: number;
  name: string | null;
  logo: string | null;
};
export type BattleAllianceResult = {
  alliance: BattleAlliance;
  members: number;
  members_max: number;
  power: number | null;
  score: number;
  server_id: number | null;
  is_blue: boolean;
  team: number | null;
};
export type CategoryMvp = {
  player_id: number;
  player_name: string;
  score: number;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type ScoreCategory = {
  alliance_score: number;
  mvp: CategoryMvp | null;
};
