// Generated by rokbattles-codegen. Do not edit.

export type AllianceAooBattleInfo = {
  metadata: MailMetadata;
  rewards: Array<Reward>;
  body: BattleInfoBody;
};
export type BattleInfoBody = {
  fights: Array<ScheduledFight>;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
export type ScheduledFight = {
  team: number;
  time: number;
  win: boolean;
};
