// Generated by rokbattles-codegen. Do not edit.

export type AllianceAooRegistration = {
  metadata: MailMetadata;
  overview: RegistrationOverview;
  participants: Array<RegistrationParticipant>;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type RegistrationOverview = {
  start_time: number;
};
export type RegistrationParticipant = {
  player_id: number;
  player_name: string;
  power: number;
  role: number;
};
