// Generated by rokbattles-codegen. Do not edit.

export type AllianceAooIndividualResults = {
  metadata: MailMetadata;
  rewards: Array<Reward>;
  body: IndividualBattleBody;
  overview: IndividualBattleOverview;
  pairings: Array<CommanderPairing>;
  results: IndividualBattleResults;
};
export type CommanderId = {
  id: number;
};
export type CommanderPairing = {
  primary_commander: CommanderId;
  secondary_commander: CommanderId;
  kill_count: number;
  battles_win: number;
  battles: number;
  severely_wounded: number;
  kill_points: number;
};
export type IndividualBattleBody = {
  type: number;
  param: number | null;
  win: boolean;
  team: number | null;
};
export type IndividualBattleOverview = {
  player_name: string | null;
  player_id: number | null;
  score: number | null;
  rank: number;
  total_results: TotalBattleResults | null;
};
export type IndividualBattleResults = {
  total_score: number | null;
  win_rate: number | null;
  battles_win: number | null;
  battles_lose: number | null;
  severely_wounded: number | null;
  kills: number | null;
  kill_score: number | null;
  flag_score: number | null;
  building_score: number | null;
  gather_score: number | null;
  healing_score: number | null;
  units_healed: number | null;
  flag_count: number | null;
  teleports: number | null;
  speedups: number | null;
  structures: number | null;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
export type TotalBattleResults = {
  battles: number;
  kill_points: number;
  severely_wounded: number;
};
