// Generated by rokbattles-codegen. Do not edit.

export type BarCanyonKillBoss = {
  metadata: MailMetadata;
  npc: CanyonNpc;
  participants: Array<CanyonParticipant>;
};
export type CanyonNpc = {
  type: number;
  level: number;
  location: Position;
};
export type CanyonParticipant = {
  player_id: number;
  player_name: string;
  avatar_url: string | null;
  frame_url: string | null;
  damage_rate: number;
  loot: Array<Reward>;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Position = {
  x: number;
  y: number;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
