// Generated by rokbattles-codegen. Do not edit.

export type Battle = {
  metadata: BattleMetadata;
  sender: BattlePlayer;
  summary: BattleSummary;
  opponents: Array<BattleOpponent>;
  timeline: BattleTimeline;
};
export type BattleAlliance = {
  id: number;
  name: string;
  abbreviation: string;
};
export type BattleArmament = {
  id: number;
  affix: string;
  buffs: string;
};
export type BattleAttack = {
  id: string;
  x: number;
  y: number;
};
export type BattleAuxiliarySkill = {
  hero_id: number;
  level: number;
  skill_id: number;
};
export type BattleCastle = {
  x: number;
  y: number;
  level: number;
  watchtower: number | null;
};
export type BattleCommander = {
  id: number | null;
  level: number | null;
  formation: number | null;
  awakened: boolean | null;
  star_level: number | null;
  equipment: string | null;
  skills: Array<BattleCommanderSkill> | null;
  relics: Array<BattleRelic> | null;
  armaments: Array<BattleArmament> | null;
};
export type BattleCommanderSkill = {
  id: number;
  level: number;
};
export type BattleCommanders = {
  primary: BattleCommander;
  secondary: BattleCommander;
};
export type BattleEffectSide = {
  modifier_sources: Array<BattleModifierSource>;
  statistics: Array<BattleEffectStatistic>;
};
export type BattleEffectStatistic = {
  source: string;
  id: number;
  stats: Array<BattleEffectValue>;
};
export type BattleEffectValue = {
  key: string;
  value: unknown;
};
export type BattleEffects = {
  sender: BattleEffectSide;
  opponent: BattleEffectSide;
};
export type BattleMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
  report_id: number;
  mail_role: string;
  kvk: boolean;
  room_id: number | null;
  schema: number | null;
  ll_script_schema: number | null;
};
export type BattleModifierSource = {
  source: string;
  ids: Array<number>;
};
export type BattleNpc = {
  type: number | null;
  b_type: number | null;
  experience: number | null;
  loot: Array<Reward> | null;
};
export type BattleOpponent = {
  player_id: number;
  player_name: string;
  kingdom_id: number | null;
  alliance: BattleAlliance;
  alliance_building_id: number | null;
  character_type: number | null;
  is_turret: boolean | null;
  is_outpost: boolean | null;
  castle: BattleCastle;
  tracking_key: string;
  camp_id: number | null;
  rally: boolean | null;
  structure_id: number | null;
  commanders: BattleCommanders;
  support_skills: BattleSupportSkills;
  auxiliary_skills: Array<BattleAuxiliarySkill>;
  app_id: number | null;
  app_uid: number | null;
  server_season: string | null;
  package_identifier: string | null;
  as_battle_type: number | null;
  session: string | null;
  avatar_url: string | null;
  frame_url: string | null;
  supreme_strife: SupremeStrife;
  attack: BattleAttack;
  start_tick: number;
  end_tick: number;
  participants: Array<BattleParticipant>;
  npc: BattleNpc;
  battle_results: BattleResults;
  battle_effects: BattleEffects;
};
export type BattleParticipant = {
  participant_id: number;
  player_id: number;
  player_name: string;
  alliance: ParticipantAlliance;
  commanders: ParticipantCommanders;
};
export type BattlePlayer = {
  player_id: number;
  player_name: string;
  kingdom_id: number | null;
  alliance: BattleAlliance;
  alliance_building_id: number | null;
  character_type: number | null;
  is_turret: boolean | null;
  is_outpost: boolean | null;
  castle: BattleCastle;
  tracking_key: string;
  camp_id: number | null;
  rally: boolean | null;
  structure_id: number | null;
  commanders: BattleCommanders;
  support_skills: BattleSupportSkills;
  auxiliary_skills: Array<BattleAuxiliarySkill>;
  app_id: number | null;
  app_uid: number | null;
  server_season: string | null;
  package_identifier: string | null;
  as_battle_type: number | null;
  session: string | null;
  avatar_url: string | null;
  frame_url: string | null;
  supreme_strife: SupremeStrife;
  participants: Array<BattleParticipant>;
};
export type BattleRelic = {
  id: number;
};
export type BattleResult = {
  reinforcements_join: number | null;
  reinforcements_leave: number | null;
  kill_points: number | null;
  acclaim: number | null;
  severely_wounded: number | null;
  slightly_wounded: number | null;
  remaining: number | null;
  dead: number | null;
  heal: number | null;
  troop_units: number | null;
  troop_units_max: number | null;
  watchtower_max: number | null;
  watchtower: number | null;
  power: number | null;
  attack_power: number | null;
  skill_power: number | null;
  merits: number | null;
  death_reduction: number | null;
  severe_wound_reduction: number | null;
};
export type BattleResults = {
  sender: BattleResult;
  opponent: BattleResult;
};
export type BattleSample = {
  tick: number;
  count: number;
};
export type BattleSummary = {
  sender: BattleSummarySide;
  opponent: BattleSummarySide;
};
export type BattleSummarySide = {
  kill_points: number | null;
  dead: number | null;
  severely_wounded: number | null;
  slightly_wounded: number | null;
  remaining: number | null;
  troop_units: number | null;
};
export type BattleSupportSkill = {
  hero_id: number;
  skill_id: number;
  skill_level: number;
};
export type BattleSupportSkills = {
  enable: boolean;
  skills: Array<BattleSupportSkill>;
};
export type BattleTimeline = {
  start_timestamp: number;
  end_timestamp: number;
  start_tick: number;
  sampling: Array<BattleSample>;
  events: Array<BattleTimelineEvent>;
};
export type BattleTimelineEvent = {
  tick: number;
  type: number;
  event_id: number | null;
  player_id: number;
  player_name: string;
  count: number | null;
  avatar_url: string | null;
  frame_url: string | null;
  commanders: ParticipantCommanders;
};
export type ParticipantAlliance = {
  abbreviation: string;
};
export type ParticipantCommander = {
  id: number | null;
  level: number | null;
};
export type ParticipantCommanders = {
  primary: ParticipantCommander;
  secondary: ParticipantCommander;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
export type SupremeStrife = {
  battle_id: string | null;
  team_id: number | null;
  round: number | null;
};
