// Generated by rokbattles-codegen. Do not edit.

export type DuelAlliance = {
  abbreviation: string;
};
export type DuelBattle2 = {
  metadata: MailMetadata;
  sender: DuelPlayer;
  opponent: DuelPlayer;
  battle_results: DuelBattleResults;
};
export type DuelBattleResults = {
  sender: DuelPlayerBattleResult;
  opponent: DuelPlayerBattleResult;
};
export type DuelBuff = {
  id: number;
  value: number;
};
export type DuelCommander = {
  id: number;
  level: number;
  star_level: number;
  awakened: boolean;
  skills: Array<DuelCommanderSkill>;
};
export type DuelCommanderSkill = {
  id: number;
  level: number;
};
export type DuelPlayer = {
  player_id: number;
  player_name: string;
  avatar_url: string | null;
  frame_url: string | null;
  alliance: DuelAlliance;
  duel: DuelTeam;
  primary_commander: DuelCommander;
  secondary_commander: DuelCommander;
  buffs: Array<DuelBuff>;
};
export type DuelPlayerBattleResult = {
  win: boolean;
  kill_points: number;
  power: number;
  units: number;
  slightly_wounded: number;
  severely_wounded: number;
  dead: number;
  heal: number;
};
export type DuelTeam = {
  team_id: number;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
