// Generated by rokbattles-codegen. Do not edit.

export type AllianceBoss = {
  id: number;
};
export type AllianceBossParticipant = {
  player_id: number;
  player_name: string;
  avatar_url: string | null;
  frame_url: string | null;
  loot: Array<Reward>;
};
export type EventMemberLootReport = {
  metadata: MailMetadata;
  boss: AllianceBoss;
  participants: Array<AllianceBossParticipant>;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
