// Generated by rokbattles-codegen. Do not edit.

export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Position = {
  x: number;
  y: number;
};
export type ResourceGathering = {
  rss_type: number;
  rss_value: number;
  rss_bonus: number;
  crystals_gain: number;
  level: number;
  time: number;
  pos: Position;
};
export type Rss = {
  metadata: MailMetadata;
  rss: ResourceGathering;
};
