// Generated by rokbattles-codegen. Do not edit.

export type BarbarianFortBody = {
  sub_type: number;
  sub_param: number;
  target_name: string;
  pos: Position;
  content: BarbarianFortContent;
};
export type BarbarianFortContent = {
  percentage: number;
  tier: number;
  level: number;
};
export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Position = {
  x: number;
  y: number;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
export type SystemBarbarianFort = {
  metadata: MailMetadata;
  rewards: Array<Reward>;
  body: BarbarianFortBody;
};
