// Generated by rokbattles-codegen. Do not edit.

export type MailMetadata = {
  mail_id: string;
  mail_time: number;
  mail_receiver: string;
  server_id: number;
};
export type Reward = {
  type: number;
  sub_type: number;
  value: number;
};
export type SystemKaharTreasure = {
  metadata: MailMetadata;
  loot: Array<Reward>;
};
