# syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e
FROM rust:1.98.1-alpine@sha256:1716b3aa042d735f4566d14dc54e8037de9d69556e2d5dd58131d93a613d173d AS container-wasm
RUN apk add --no-cache build-base openssl-dev pkgconfig
RUN --mount=type=bind,source=.,target=/src \
    --mount=type=cache,id=rokbattles-cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=rokbattles-cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=rokbattles-cargo-target-wasm,target=/target,sharing=locked \
    CARGO_TARGET_DIR=/target CONTAINER_WASM_OUT_DIR=/out \
    sh /src/packages/site/scripts/build-container.sh

FROM node:26-alpine@sha256:2d984a15c9b54fd0aeb608b8e0d0d83529eb34d2966db27a1fb4f1edc3d298a3 AS base
WORKDIR /app

FROM base AS builder
ARG API_URL
ENV API_URL=${API_URL}
RUN apk add --no-cache git libc6-compat
COPY --link pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY --link packages/site/package.json ./packages/site/package.json
RUN npm install --global corepack@0.36.0 && corepack enable pnpm
RUN --mount=type=cache,id=rokbattles-pnpm-store,target=/pnpm/store \
    pnpm config set store-dir /pnpm/store && \
    pnpm install --frozen-lockfile
COPY --link packages/site ./packages/site
COPY --from=container-wasm /out ./packages/site/src/autogenerated/container
COPY --link datasets ./datasets
RUN pnpm --filter=@rokbattles/site... run sync:legal
RUN pnpm --filter=@rokbattles/site... run generate:datasets
RUN pnpm --filter=@rokbattles/site... build

FROM base AS runner
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/.next/static ./packages/site/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/public ./packages/site/public
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/legal ./packages/site/legal
WORKDIR /app/packages/site
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
