# syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12
FROM rust:1.98.0-alpine@sha256:a10e64dd139b7387337c7fbe8aca31b959b57b2fd4c8ae20a02cf1d6ea424dce AS container-wasm
RUN apk add --no-cache build-base openssl-dev pkgconfig
RUN --mount=type=bind,source=.,target=/src \
    --mount=type=cache,id=rokbattles-cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=rokbattles-cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=rokbattles-cargo-target-wasm,target=/target,sharing=locked \
    CARGO_TARGET_DIR=/target CONTAINER_WASM_OUT_DIR=/out \
    sh /src/packages/site/scripts/build-container.sh

FROM node:24-alpine@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd AS base
WORKDIR /app

FROM base AS builder
ARG API_URL
ENV API_URL=${API_URL}
RUN apk add --no-cache git libc6-compat
COPY --link pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY --link packages/site/package.json ./packages/site/package.json
RUN corepack enable pnpm
RUN --mount=type=cache,id=rokbattles-pnpm-store,target=/pnpm/store \
    pnpm config set store-dir /pnpm/store && \
    pnpm install --frozen-lockfile
COPY --link packages/site ./packages/site
COPY --from=container-wasm /out ./packages/site/src/autogenerated/container
COPY --link datasets ./datasets
RUN pnpm --filter=@rokbattles/site... run sync:legal
RUN pnpm --filter=@rokbattles/site... run generate:datasets
RUN pnpm --filter=@rokbattles/site... build

FROM base AS runner
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/.next/static ./packages/site/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/public ./packages/site/public
COPY --from=builder --chown=nextjs:nodejs /app/packages/site/legal ./packages/site/legal
WORKDIR /app/packages/site
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
