"use client";

import formationsData from "@/autogenerated/formations.json";
import { defaultLocale } from "@/i18n/config";
import { resolveDatasetLocale } from "@/i18n/dataset-locale";

const formationMap = formationsData.formations;

type FormationIdKey = keyof typeof formationMap;
type FormationEntry = (typeof formationMap)[FormationIdKey];
type FormationLocale = keyof FormationEntry["name"];

export function getFormationName(
  id: number | null | undefined,
  locale?: string
) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const formation = formationMap[String(id) as FormationIdKey];
  if (!formation) {
    return undefined;
  }

  const requestedLocale = resolveDatasetLocale(locale);
  return (
    (formation.name as Record<string, string | undefined>)[requestedLocale] ??
    formation.name[defaultLocale as FormationLocale]
  );
}
