"use client";

import commandersData from "@/autogenerated/commanders.json";
import { defaultLocale } from "@/i18n/config";
import { resolveDatasetLocale } from "@/i18n/dataset-locale";

const commanderMap = commandersData.commanders;

type CommanderIdKey = keyof typeof commanderMap;
type CommanderEntry = (typeof commanderMap)[CommanderIdKey];
type CommanderLocale = keyof CommanderEntry["name"];

export function getCommanderName(
  id: number | null | undefined,
  locale?: string
) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander) {
    return undefined;
  }

  const requestedLocale = resolveDatasetLocale(locale);
  return (
    (commander.name as Record<string, string | undefined>)[requestedLocale] ??
    commander.name[defaultLocale as CommanderLocale]
  );
}

export type CommanderOption = {
  id: number;
  name: string;
};

export function useCommanderOptions(locale?: string) {
  const requestedLocale = resolveDatasetLocale(locale);
  const entries = Object.entries(commanderMap).map(([id, commander]) => {
    const localizedName =
      commander.name[requestedLocale as CommanderLocale] ??
      commander.name[defaultLocale as CommanderLocale] ??
      String(id);

    return {
      id: Number(id),
      name: localizedName,
    };
  });

  return entries.sort((a, b) => a.name.localeCompare(b.name));
}
