"use client";

import armamentsData from "@/autogenerated/armaments.json";
import { defaultLocale } from "@/i18n/config";
import { resolveDatasetLocale } from "@/i18n/dataset-locale";

const armamentMap = armamentsData.armaments;

type ArmamentIdKey = keyof typeof armamentMap;
type ArmamentEntry = (typeof armamentMap)[ArmamentIdKey];
type ArmamentLocale = keyof ArmamentEntry["name"];

interface ArmamentInfo {
  name: string;
  percent: boolean;
}

export function getArmamentInfo(
  id: number | null | undefined,
  locale?: string
): ArmamentInfo | undefined {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const armament = armamentMap[String(id) as ArmamentIdKey];
  if (!armament) {
    return undefined;
  }

  const requestedLocale = resolveDatasetLocale(locale);
  const name =
    (armament.name as Record<string, string | undefined>)[requestedLocale] ??
    armament.name[defaultLocale as ArmamentLocale];
  const percent =
    typeof armament.percent === "boolean" ? armament.percent : true;
  return name ? { name, percent } : undefined;
}
