"use client";

import equipmentData from "@/autogenerated/equipment.json";
import { defaultLocale } from "@/i18n/config";
import { resolveDatasetLocale } from "@/i18n/dataset-locale";

const equipmentMap = equipmentData.equipment.item;

type EquipmentIdKey = keyof typeof equipmentMap;
type EquipmentEntry = (typeof equipmentMap)[EquipmentIdKey];
type EquipmentLocale = keyof EquipmentEntry["name"];

export function getEquipmentName(
  id: number | null | undefined,
  locale?: string
) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const equipment = equipmentMap[String(id) as EquipmentIdKey];
  if (!equipment) {
    return undefined;
  }

  const requestedLocale = resolveDatasetLocale(locale);
  return (
    (equipment.name as Record<string, string | undefined>)[requestedLocale] ??
    equipment.name[defaultLocale as EquipmentLocale]
  );
}
