"use client";

import inscriptionsData from "@/autogenerated/inscriptions.json";
import { defaultLocale } from "@/i18n/config";
import { resolveDatasetLocale } from "@/i18n/dataset-locale";

const inscriptionMap = inscriptionsData.inscriptions;

type InscriptionIdKey = keyof typeof inscriptionMap;
type InscriptionEntry = (typeof inscriptionMap)[InscriptionIdKey];
type InscriptionLocale = keyof InscriptionEntry["name"];

export function getInscriptionName(
  id: number | null | undefined,
  locale?: string
) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const inscription = inscriptionMap[String(id) as InscriptionIdKey];
  if (!inscription) {
    return undefined;
  }

  const requestedLocale = resolveDatasetLocale(locale);
  return (
    (inscription.name as Record<string, string | undefined>)[requestedLocale] ??
    inscription.name[defaultLocale as InscriptionLocale]
  );
}
