"use client";

import { cache, useMemo } from "react";
import armamentsData from "@/autogenerated/armaments.json";

const DEFAULT_LOCALE = "en";

const armamentMap = armamentsData.armaments;

type ArmamentIdKey = keyof typeof armamentMap;
type ArmamentEntry = (typeof armamentMap)[ArmamentIdKey];
type ArmamentLocale = keyof ArmamentEntry["name"];

const resolveArmamentNameInternal = cache(
  (id: number | null | undefined, locale: string = DEFAULT_LOCALE) => {
    if (typeof id !== "number" || !Number.isFinite(id) || id <= 0) {
      return undefined;
    }

    const armament = armamentMap[String(id) as ArmamentIdKey];
    if (!armament) {
      return undefined;
    }

    const requestedLocale = locale ?? DEFAULT_LOCALE;
    return (
      (armament.name as Record<string, string | undefined>)[requestedLocale] ??
      armament.name[DEFAULT_LOCALE as ArmamentLocale]
    );
  }
);

export function useArmamentName(id: number | null | undefined, locale = DEFAULT_LOCALE) {
  return useMemo(() => resolveArmamentNameInternal(id, locale), [id, locale]);
}
