"use client";

import armamentsData from "@/autogenerated/armaments.json";

const DEFAULT_LOCALE = "en";

const armamentMap = armamentsData.armaments;

type ArmamentIdKey = keyof typeof armamentMap;
type ArmamentEntry = (typeof armamentMap)[ArmamentIdKey];
type ArmamentLocale = keyof ArmamentEntry["name"];

type ArmamentInfo = {
  name: string;
  percent: boolean;
};

export function getArmamentInfo(
  id: number | null | undefined,
  locale = DEFAULT_LOCALE
): ArmamentInfo | undefined {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const armament = armamentMap[String(id) as ArmamentIdKey];
  if (!armament) {
    return undefined;
  }

  const requestedLocale = locale ?? DEFAULT_LOCALE;
  const name =
    (armament.name as Record<string, string | undefined>)[requestedLocale] ??
    armament.name[DEFAULT_LOCALE as ArmamentLocale];
  const percent = typeof armament.percent === "boolean" ? armament.percent : true;
  return name ? { name, percent } : undefined;
}
