"use client";

import { cache, useMemo } from "react";
import armamentsData from "@/autogenerated/armaments.json";

const DEFAULT_LOCALE = "en";

const armamentMap = armamentsData.armaments;

type ArmamentIdKey = keyof typeof armamentMap;
type ArmamentEntry = (typeof armamentMap)[ArmamentIdKey];
type ArmamentLocale = keyof ArmamentEntry["name"];

type ArmamentInfo = {
  name: string;
  percent: boolean;
};

const resolveArmamentInternal = cache(
  (id: number | null | undefined, locale: string = DEFAULT_LOCALE): ArmamentInfo | undefined => {
    if (typeof id !== "number" || !Number.isFinite(id) || id <= 0) {
      return undefined;
    }

    const armament = armamentMap[String(id) as ArmamentIdKey];
    if (!armament) {
      return undefined;
    }

    const requestedLocale = locale ?? DEFAULT_LOCALE;
    const name =
      (armament.name as Record<string, string | undefined>)[requestedLocale] ??
      armament.name[DEFAULT_LOCALE as ArmamentLocale];
    const percent = typeof armament.percent === "boolean" ? armament.percent : true;
    return name ? { name, percent } : undefined;
  }
);

export function useArmamentName(id: number | null | undefined, locale = DEFAULT_LOCALE) {
  return useMemo(() => resolveArmamentInternal(id, locale)?.name, [id, locale]);
}

export function useArmamentInfo(
  id: number | null | undefined,
  locale = DEFAULT_LOCALE
): ArmamentInfo | undefined {
  return useMemo(() => resolveArmamentInternal(id, locale), [id, locale]);
}

export function getArmamentInfo(
  id: number | null | undefined,
  locale = DEFAULT_LOCALE
): ArmamentInfo | undefined {
  return resolveArmamentInternal(id, locale);
}
