"use client";

import equipmentData from "@/autogenerated/equipment.json";

const DEFAULT_LOCALE = "en";

const equipmentMap = equipmentData.equipment.item;

type EquipmentIdKey = keyof typeof equipmentMap;
type EquipmentEntry = (typeof equipmentMap)[EquipmentIdKey];
type EquipmentLocale = keyof EquipmentEntry["name"];

export function getEquipmentName(id: number | null | undefined, locale = DEFAULT_LOCALE) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const equipment = equipmentMap[String(id) as EquipmentIdKey];
  if (!equipment) {
    return undefined;
  }

  const requestedLocale = locale ?? DEFAULT_LOCALE;
  return (
    (equipment.name as Record<string, string | undefined>)[requestedLocale] ??
    equipment.name[DEFAULT_LOCALE as EquipmentLocale]
  );
}
