"use client";

import { cache, useMemo } from "react";
import formationsData from "@/autogenerated/formations.json";

const DEFAULT_LOCALE = "en";

const formationMap = formationsData.formations;

type FormationIdKey = keyof typeof formationMap;
type FormationEntry = (typeof formationMap)[FormationIdKey];
type FormationLocale = keyof FormationEntry["name"];

const resolveFormationNameInternal = cache(
  (id: number | null | undefined, locale: string = DEFAULT_LOCALE) => {
    if (typeof id !== "number" || !Number.isFinite(id) || id <= 0) {
      return undefined;
    }

    const formation = formationMap[String(id) as FormationIdKey];
    if (!formation) {
      return undefined;
    }

    const requestedLocale = locale ?? DEFAULT_LOCALE;
    return (
      (formation.name as Record<string, string | undefined>)[requestedLocale] ??
      formation.name[DEFAULT_LOCALE as FormationLocale]
    );
  }
);

export function useFormationName(id: number | null | undefined, locale = DEFAULT_LOCALE) {
  return useMemo(() => resolveFormationNameInternal(id, locale), [id, locale]);
}
