"use client";

import { cache, useMemo } from "react";
import inscriptionsData from "@/autogenerated/inscriptions.json";

const DEFAULT_LOCALE = "en";

const inscriptionMap = inscriptionsData.inscriptions;

type InscriptionIdKey = keyof typeof inscriptionMap;
type InscriptionEntry = (typeof inscriptionMap)[InscriptionIdKey];
type InscriptionLocale = keyof InscriptionEntry["name"];

const resolveInscriptionNameInternal = cache(
  (id: number | null | undefined, locale: string = DEFAULT_LOCALE) => {
    if (typeof id !== "number" || !Number.isFinite(id) || id <= 0) {
      return undefined;
    }

    const inscription = inscriptionMap[String(id) as InscriptionIdKey];
    if (!inscription) {
      return undefined;
    }

    const requestedLocale = locale ?? DEFAULT_LOCALE;
    return (
      (inscription.name as Record<string, string | undefined>)[requestedLocale] ??
      inscription.name[DEFAULT_LOCALE as InscriptionLocale]
    );
  }
);

export function useInscriptionName(id: number | null | undefined, locale = DEFAULT_LOCALE) {
  return useMemo(() => resolveInscriptionNameInternal(id, locale), [id, locale]);
}
