import init, { MapEngine } from "@/autogenerated/map-engine/rokbattles_webgpu_map_engine";
import {
  buildingRules,
  buildStructureBoundarySegments,
  buildTerritoryOverviewsFromOwnership,
  snapTerritoryPoint,
  TERRITORY_UNIT,
  territoryBounds,
} from "@/lib/territory/geometry";
import { routeCommanderSprite } from "@/lib/territory-lab/commander-sprites";
import { orderedRouteSites } from "@/lib/territory-lab/routes";
import {
  legacyBuilding,
  mapStructures,
  placementError,
  territorySummary,
} from "@/lib/territory-lab/territory";
import {
  type BuildingKind,
  type Catalog,
  CDN,
  type MapData,
  PALETTE,
  type Plan,
  type Point,
  type Route,
  type RouteLeg,
  type Site,
  SPRITES,
} from "@/lib/territory-lab/types";

type Overlay = {
  position: Point;
  size: Point;
  texture: string;
  color: number[];
  worldSize: boolean;
  offset?: Point;
  detailOnly?: boolean;
  minZoom?: number;
  strokeWidth?: number;
  dashed?: boolean;
};
export type CameraStatus = { backend: string; zoom: number; scale: number };
export type MapVisibility = {
  resources: boolean;
  allianceTags: boolean;
  caves: boolean;
  villages: boolean;
};
let initialized: Promise<unknown> | undefined;

function rgba(color: string, alpha = 1) {
  return [1, 3, 5].map((i) => Number.parseInt(color.slice(i, i + 2), 16) / 255).concat(alpha);
}

function glyphAtlas() {
  const canvas = document.createElement("canvas");
  canvas.width = 384;
  canvas.height = 240;
  const ctx = canvas.getContext("2d", { willReadFrequently: true });
  if (!ctx) throw new Error("Could not create the text atlas.");
  ctx.font = "32px monospace";
  ctx.fillStyle = "white";
  ctx.textBaseline = "middle";
  ctx.textAlign = "center";
  for (let i = 0; i < 95; i++)
    ctx.fillText(String.fromCharCode(i + 32), (i % 16) * 24 + 12, Math.floor(i / 16) * 40 + 20);
  return new Uint8Array(ctx.getImageData(0, 0, 384, 240).data);
}

/** Owns one canvas/device. Disposal also aborts fetches and releases decoded images. */
export class LabController {
  engine!: MapEngine;
  canvas!: HTMLCanvasElement;
  private resizeObserver?: ResizeObserver;
  private abort = new AbortController();
  private disposed = false;
  private frame = 0;
  private imageSizes = new Map<string, Point>();
  private plan?: Plan;
  private legs: RouteLeg[] = [];
  private selected = new Set<string>();
  private visibility: MapVisibility = {
    resources: true,
    allianceTags: true,
    caves: false,
    villages: false,
  };
  private placement?: { kind: BuildingKind; allianceId: string; x: number; y: number };
  private labelCache = new Map<string, { signature: string; size: Point }>();
  private portraits = new Map<string, { signature: string; size?: Point }>();
  private portraitWork: Promise<void> = Promise.resolve();
  constructor(
    private host: HTMLDivElement,
    private readonly catalog: Catalog,
    private readonly data: MapData,
    private statusCallback: (status: CameraStatus) => void,
    private failure: (message: string) => void
  ) {}

  async start(forceWebgl = false) {
    initialized ??= init();
    await initialized;
    if (this.disposed) return;
    const config = JSON.stringify({
      name: this.catalog.name,
      bounds: this.catalog.bounds,
    });
    const create = async (webgl: boolean) => {
      this.canvas = document.createElement("canvas");
      this.canvas.tabIndex = 0;
      this.canvas.setAttribute("aria-label", `${this.catalog.name} planning canvas`);
      this.host.replaceChildren(this.canvas);
      return MapEngine.create_raster(this.canvas, config, glyphAtlas(), webgl);
    };
    try {
      this.engine = await create(forceWebgl);
    } catch (error) {
      if (forceWebgl || this.disposed) throw error;
      // A canvas cannot switch context types. Replace it before the WebGL retry.
      this.engine = await create(true);
    }
    if (this.disposed) {
      this.engine.free();
      return;
    }
    this.resizeObserver = new ResizeObserver(() => this.resize());
    this.resizeObserver.observe(this.host);
    this.engine.set_forbidden(this.data.forbiddenBytes);
    this.resize();
    for (const mode of ["overview", "detail"]) {
      await this.loadImage(mode, `${CDN}/${this.catalog.map}/${mode}.webp`);
      if (this.disposed) return;
      this.render();
    }
    const icons = new Set([
      ...Object.values(this.catalog.structureIcons),
      ...Object.values(this.catalog.buildingIcons),
      ...Object.values(this.catalog.siteIcons),
    ]);
    // Small icon requests are bounded, unlike full map/mesh decoding.
    const remaining = [...icons];
    await Promise.all(
      Array.from({ length: 3 }, async () => {
        for (let key = remaining.shift(); key; key = remaining.shift())
          await this.loadImage(key, `${SPRITES}/${key}`);
      })
    );
    this.render();
  }

  private async loadImage(key: string, url: string) {
    // A thumbnail fetched without CORS in an older page can poison the browser
    // image cache. Revalidate before reading pixels for GPU upload.
    const response = await fetch(url, { signal: this.abort.signal, cache: "no-cache" });
    if (!response.ok) throw new Error(`Could not load map artwork (${response.status}).`);
    const bitmap = await createImageBitmap(await response.blob(), { premultiplyAlpha: "none" });
    if (this.disposed) {
      bitmap.close();
      return;
    }
    try {
      const canvas = document.createElement("canvas");
      canvas.width = bitmap.width;
      canvas.height = bitmap.height;
      const ctx = canvas.getContext("2d", { willReadFrequently: true });
      if (!ctx) throw new Error("Could not decode the map artwork.");
      ctx.drawImage(bitmap, 0, 0);
      this.engine.upload_image(
        key,
        bitmap.width,
        bitmap.height,
        new Uint8Array(ctx.getImageData(0, 0, bitmap.width, bitmap.height).data)
      );
      // Only sprite aspect ratios are needed after the pixels reach the GPU.
      this.imageSizes.set(key, [bitmap.width, bitmap.height]);
    } finally {
      bitmap.close();
    }
  }

  resize() {
    if (!this.engine || this.disposed) return;
    this.engine.resize(
      this.host.clientWidth,
      this.host.clientHeight,
      Math.min(devicePixelRatio, 2)
    );
    this.render();
  }
  world(x: number, y: number): Point {
    const p = this.engine.screen_to_world(x, y);
    return [p[0], p[1]];
  }
  screen(x: number, y: number): Point {
    const p = this.engine.world_to_screen(x, y);
    return [p[0], p[1]];
  }
  pan(x: number, y: number) {
    this.engine.pan(x, y);
    this.render();
  }
  zoom(factor: number, x = this.host.clientWidth / 2, y = this.host.clientHeight / 2) {
    this.engine.zoom(factor, x, y);
    this.render();
  }
  locate(x: number, y: number) {
    const status: CameraStatus = JSON.parse(this.engine.status());
    this.engine.zoom(4 / status.zoom, this.host.clientWidth / 2, this.host.clientHeight / 2);
    const point = this.screen(x, y);
    this.pan(this.host.clientWidth / 2 - point[0], this.host.clientHeight / 2 - point[1]);
  }

  update(plan: Plan, selected: Set<string>, legs: RouteLeg[], visibility: MapVisibility) {
    this.plan = plan;
    this.selected = selected;
    this.legs = legs;
    this.visibility = visibility;
    this.preparePortraits();
    this.rebuild();
    this.render();
  }

  previewPlacement(kind: BuildingKind, allianceId: string, x: number, y: number) {
    this.placement = { kind, allianceId, x, y };
    this.render();
  }

  setPlacementTool(tool: string, allianceId: string) {
    if (
      this.placement &&
      (this.placement.kind !== tool || this.placement.allianceId !== allianceId)
    )
      this.clearPlacement();
  }

  clearPlacement() {
    this.placement = undefined;
    if (this.engine && !this.disposed) this.engine.set_preview("[]");
    this.render();
  }

  private rebuildPlacement() {
    if (!this.placement || !this.plan) return;
    const { kind, allianceId, x, y } = this.placement;
    const point = this.world(x, y);
    const building = {
      id: "preview",
      kind,
      allianceId,
      x: Math.round(point[0] * 100) / 100,
      y: Math.round(point[1] * 100) / 100,
    };
    const legacy = legacyBuilding(building);
    const bounds = territoryBounds(legacy);
    const center = snapTerritoryPoint(building.x, building.y);
    const legal = !placementError(building, this.plan, this.catalog, this.data);
    const color = legal ? "#22C55E" : "#EF4444";
    const footprint: Overlay = {
      position: [center.x, center.y],
      size: [bounds.maxX - bounds.minX, bounds.maxY - bounds.minY],
      texture: "white",
      color: rgba(color, 0.22),
      worldSize: true,
    };
    const overlays: Overlay[] = [
      footprint,
      { ...footprint, color: rgba(color), strokeWidth: 2, dashed: true },
      {
        ...footprint,
        size: [TERRITORY_UNIT, TERRITORY_UNIT],
        color: [1, 1, 1, 0.9],
        strokeWidth: 1,
      },
      {
        ...footprint,
        position: [building.x, building.y],
        size: [
          buildingRules[legacy.kind].baseClearance * 2,
          buildingRules[legacy.kind].baseClearance * 2,
        ],
        color: rgba(color),
        strokeWidth: 1,
      },
    ];
    // A fixed-size reticle stays visible even when the placement cell is tiny.
    for (const size of [
      [18, 2],
      [2, 18],
    ] as Point[])
      overlays.push({
        position: [building.x, building.y],
        size,
        texture: "white",
        color: [1, 1, 1, 0.95],
        worldSize: false,
      });
    overlays.push({
      position: [building.x, building.y],
      size: [4, 4],
      texture: "white",
      color: rgba(color),
      worldSize: false,
    });
    this.engine.set_preview(JSON.stringify(overlays));
  }

  private rebuild(exporting = false) {
    const plan = this.plan;
    if (!plan || !this.engine) return;
    const overlays: Overlay[] = [];
    const sprite = (
      key: string | undefined,
      p: Point,
      size = 26,
      color = [1, 1, 1, 1],
      detailOnly = false,
      minZoom = 0
    ) => {
      if (!key) return;
      const image = this.imageSizes.get(key);
      overlays.push({
        position: p,
        size: [size * (image ? image[0] / image[1] : 1), size],
        texture: key,
        color,
        worldSize: false,
        detailOnly,
        minZoom,
      });
    };
    if (plan.mode === "territory") {
      const { ownership } = territorySummary(
        plan,
        this.catalog,
        this.data,
        plan.alliances[0]?.id ?? ""
      );
      for (const [allianceId, overview] of buildTerritoryOverviewsFromOwnership(ownership)) {
        const color = plan.alliances.find((a) => a.id === allianceId)?.color ?? PALETTE[4];
        for (const r of overview.fillRects)
          overlays.push({
            position: [(r.minX + r.maxX) / 2, (r.minY + r.maxY) / 2],
            size: [r.maxX - r.minX, r.maxY - r.minY],
            texture: "white",
            color: rgba(color, 0.28),
            worldSize: true,
          });
      }
    }
    if (plan.mode === "territory") {
      const structures = mapStructures(this.catalog, this.data);
      for (const [radiusKey, strokeWidth, alpha] of [
        ["territoryRadiusInCells", 1.6, 0.78],
        ["teleportRadiusInCells", 1, 0.45],
      ] as const) {
        for (const { x1, y1, x2, y2 } of buildStructureBoundarySegments(structures, radiusKey)) {
          overlays.push({
            position: [(x1 + x2) / 2, (y1 + y2) / 2],
            size: [x2 - x1, y2 - y1],
            texture: "white",
            color: [0.153, 0.153, 0.165, alpha],
            worldSize: true,
            detailOnly: true,
            strokeWidth,
            dashed: true,
          });
        }
      }
    }
    for (const site of this.visibleSites()) {
      const size = site.id.startsWith("canyons:") ? 18 : site.kind === "pass" ? 22 : 28;
      const key = site.strongholdType
        ? this.catalog.structureIcons[String(site.strongholdType)]
        : this.catalog.siteIcons[site.kind];
      const route = plan.routes.find(
        (r) => r.siteIds.includes(site.id) || r.passes.some((p) => p.siteId === site.id)
      );
      if (route)
        overlays.push({
          position: [site.x, site.y],
          size: [size + 5, size + 5],
          texture: "white",
          color: rgba(route.color, 0.5),
          worldSize: false,
        });
      sprite(key, [site.x, site.y], size, [0.902, 0.902, 0.902, 1]);
      if (plan.mode === "baulur" && site.kind === "pass" && this.visibility.allianceTags) {
        const assigned = route?.passes.find((pass) => pass.siteId === site.id);
        const alliance = plan.alliances.find((value) => value.id === assigned?.allianceId);
        if (alliance)
          this.label(
            `alliance-${alliance.id}`,
            alliance.name,
            alliance.color,
            0,
            [site.x, site.y],
            overlays,
            [0, -27]
          );
      }
    }
    if (this.visibility.resources && plan.mode === "territory")
      for (const r of this.data.resources)
        sprite(this.catalog.siteIcons[r.kind], [r.x, r.y], 16, [1, 1, 1, 1], false, 3);
    for (const landmark of plan.mode === "territory" ? this.data.landmarks : []) {
      if (landmark.kind === "cave" ? this.visibility.caves : this.visibility.villages)
        sprite(
          this.catalog.siteIcons[landmark.kind],
          [landmark.x, landmark.y],
          20,
          [1, 1, 1, 1],
          true
        );
    }
    for (const b of plan.buildings) {
      if (b.kind !== "horse") {
        const bounds = territoryBounds(legacyBuilding(b));
        const color =
          plan.alliances.find((alliance) => alliance.id === b.allianceId)?.color ?? PALETTE[4];
        overlays.push({
          position: [(bounds.minX + bounds.maxX) / 2, (bounds.minY + bounds.maxY) / 2],
          size: [bounds.maxX - bounds.minX, bounds.maxY - bounds.minY],
          texture: "white",
          color: rgba(color),
          worldSize: true,
          strokeWidth: 1.6,
          minZoom: 10,
        });
      }
      if (!exporting && this.selected.has(b.id))
        overlays.push({
          position: [b.x, b.y],
          size: [30, 30],
          texture: "white",
          color: [1, 1, 1, 0.5],
          worldSize: false,
          minZoom: b.kind === "flag" ? 5 : 0,
        });
      sprite(
        this.catalog.buildingIcons[b.kind],
        [b.x, b.y],
        b.kind === "flag" ? 24 : 30,
        [1, 1, 1, 1],
        false,
        b.kind === "flag" ? 5 : 0
      );
      if (b.kind !== "flag" && this.visibility.allianceTags) {
        const alliance = plan.alliances.find((a) => a.id === b.allianceId);
        if (alliance)
          this.label(
            `alliance-${alliance.id}`,
            alliance.name,
            alliance.color,
            0,
            [b.x, b.y],
            overlays,
            [0, -28]
          );
      }
    }
    let id = 1;
    const objects: unknown[] = [];
    for (const a of plan.mode === "territory" ? plan.annotations : []) {
      const style = {
        color: Math.max(0, PALETTE.indexOf(a.color.toUpperCase())) + 1,
        size: a.width,
      };
      if (a.kind === "text") {
        // Labels use their own texture so commander/player names can contain Unicode.
        this.label(a.id, a.text ?? "", a.color, a.width, a.points[0], overlays);
      } else if (a.kind === "marker")
        objects.push({ kind: "marker", id: id++, x: a.points[0][0], y: a.points[0][1], style });
      else
        objects.push({
          kind: "drawing",
          id: id++,
          points: a.points,
          shape: a.kind === "line" ? "freehand" : a.kind,
          style,
        });
    }
    if (plan.mode === "baulur") {
      for (const route of plan.routes) {
        const startId = orderedRouteSites(route)[0];
        const start = this.data.sites.find((site) => site.id === startId);
        if (!start) continue;
        const portrait = this.portraits.get(route.id);
        if (portrait?.size)
          overlays.push({
            position: [start.x, start.y],
            size: portrait.size,
            texture: `label-route-start-${route.id}`,
            color: [1, 1, 1, 1],
            worldSize: false,
            offset: [0, -32],
          });
        else
          objects.push({
            kind: "marker",
            id: id++,
            x: start.x,
            y: start.y,
            style: { color: Math.max(0, PALETTE.indexOf(route.color.toUpperCase())) + 1, size: 2 },
          });
      }
    }
    for (const leg of this.legs) {
      const route = plan.routes.find((r) => r.id === leg.routeId);
      if (route && leg.path)
        objects.push({
          kind: "drawing",
          id: id++,
          points: leg.path,
          shape: "freehand",
          style: { color: Math.max(0, PALETTE.indexOf(route.color.toUpperCase())) + 1, size: 2 },
        });
    }
    this.engine.set_overlays(JSON.stringify(overlays));
    const usedTextures = new Set(overlays.map((overlay) => overlay.texture));
    for (const key of this.labelCache.keys()) {
      if (!usedTextures.has(key)) this.labelCache.delete(key);
    }
    this.engine.import_document(JSON.stringify({ version: 1, objects }));
    for (const a of plan.mode === "territory" ? plan.annotations : []) {
      if (exporting || !this.selected.has(a.id) || a.kind === "text") continue;
      const point = a.kind === "circle" ? a.points[1] : a.points[0];
      const [x, y] = this.screen(...point);
      this.engine.select(x, y, true);
    }
  }

  private preparePortraits() {
    if (this.plan?.mode !== "baulur") return;
    for (const route of this.plan.routes) {
      if (!route.siteIds.length) {
        this.portraits.delete(route.id);
        continue;
      }
      const signature = route.commander;
      if (this.portraits.get(route.id)?.signature === signature) continue;
      this.portraits.set(route.id, { signature });
      // Decode portraits one at a time; changing a selection invalidates its queued result.
      this.portraitWork = this.portraitWork
        .then(async () => {
          if (this.disposed || this.portraits.get(route.id)?.signature !== signature) return;
          await this.loadPortrait(route, signature);
        })
        .catch(() => {
          // Keep the route marker when an optional portrait is unavailable.
        });
    }
  }

  private async loadPortrait(route: Route, signature: string) {
    const url = routeCommanderSprite(route.commander);
    if (!url) return;
    const canvas = document.createElement("canvas");
    canvas.width = 40;
    canvas.height = 40;
    const ctx = canvas.getContext("2d", { willReadFrequently: true });
    if (!ctx) return;
    const response = await fetch(url, { signal: this.abort.signal, cache: "no-cache" });
    if (!response.ok) throw new Error("Commander portrait unavailable.");
    const bitmap = await createImageBitmap(await response.blob());
    try {
      const scale = Math.min(40 / bitmap.width, 40 / bitmap.height);
      const width = bitmap.width * scale,
        height = bitmap.height * scale;
      ctx.drawImage(bitmap, (40 - width) / 2, (40 - height) / 2, width, height);
    } finally {
      bitmap.close();
    }
    if (this.disposed || this.portraits.get(route.id)?.signature !== signature) return;
    this.engine.upload_image(
      `label-route-start-${route.id}`,
      canvas.width,
      canvas.height,
      new Uint8Array(ctx.getImageData(0, 0, canvas.width, canvas.height).data)
    );
    this.portraits.set(route.id, { signature, size: [canvas.width, canvas.height] });
    this.rebuild();
    this.render();
  }

  private label(
    id: string,
    text: string,
    color: string,
    width: number,
    position: Point,
    overlays: Overlay[],
    offset: Point = [0, 0]
  ) {
    const key = `label-${id}`;
    const signature = JSON.stringify([text, color, width, this.selected.has(id)]);
    const cached = this.labelCache.get(key);
    if (cached?.signature === signature) {
      overlays.push({
        position,
        size: cached.size,
        texture: key,
        color: [1, 1, 1, 1],
        worldSize: false,
        offset,
      });
      return;
    }
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d", { willReadFrequently: true });
    if (!ctx) return;
    const size = 13 + width * 3;
    ctx.font = `600 ${size}px system-ui`;
    const measure = ctx.measureText(text);
    canvas.width = Math.min(4096, Math.ceil(measure.width) + 12);
    canvas.height = size + 14;
    ctx.font = `600 ${size}px system-ui`;
    ctx.fillStyle = this.selected.has(id) ? "#536574" : "#09121de6";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = color;
    ctx.textBaseline = "middle";
    ctx.fillText(text, 6, canvas.height / 2);
    this.engine.upload_image(
      key,
      canvas.width,
      canvas.height,
      new Uint8Array(ctx.getImageData(0, 0, canvas.width, canvas.height).data)
    );
    this.labelCache.set(key, { signature, size: [canvas.width, canvas.height] });
    overlays.push({
      position,
      size: [canvas.width, canvas.height],
      texture: key,
      color: [1, 1, 1, 1],
      worldSize: false,
      offset,
    });
  }

  private visibleSites() {
    return this.data.sites.filter((site) =>
      this.plan?.mode === "baulur"
        ? site.id.startsWith("canyons:") || site.kind === "pass"
        : !site.id.startsWith("canyons:")
    );
  }
  pickSite(x: number, y: number): Site | undefined {
    return this.visibleSites()
      .map((site) => ({ site, p: this.screen(site.x, site.y) }))
      .filter(({ p }) => Math.hypot(x - p[0], y - p[1]) < 20)
      .sort((a, b) => Math.hypot(x - a.p[0], y - a.p[1]) - Math.hypot(x - b.p[0], y - b.p[1]))[0]
      ?.site;
  }

  render() {
    if (this.disposed || !this.engine || this.frame) return;
    this.frame = requestAnimationFrame(() => {
      this.frame = 0;
      try {
        this.rebuildPlacement();
        this.engine.render();
        this.statusCallback(JSON.parse(this.engine.status()));
      } catch (error) {
        this.failure(String(error));
      }
    });
  }

  beginDraft(kind: string, x: number, y: number, color: string, width: number) {
    this.engine.set_style(Math.max(0, PALETTE.indexOf(color)) + 1, width);
    this.engine.begin_drawing(kind === "line" ? "drawing" : kind, x, y);
  }
  draftPoint(x: number, y: number) {
    this.engine.draw_point(x, y);
    this.render();
  }
  cancelDraft() {
    this.engine.cancel_drawing();
    this.render();
  }

  /** Export the whole map at its catalog resolution, then restore the editing camera. */
  async png(): Promise<Blob> {
    await this.portraitWork;
    const before = JSON.parse(this.engine.status());
    const [width, height] = this.catalog.pixelSize;
    cancelAnimationFrame(this.frame);
    this.frame = 0;
    try {
      this.engine.set_preview("[]");
      // Export supplied overlays without selection highlights or interactive zoom fades.
      this.rebuild(true);
      this.engine.resize(width, height, 1);
      this.engine.fit();
      this.engine.zoom(1 / 0.94, width / 2, height / 2);
      this.engine.render_export();
      return await new Promise<Blob>((resolve, reject) =>
        this.canvas.toBlob(
          (blob) => (blob ? resolve(blob) : reject(new Error("PNG export failed."))),
          "image/png"
        )
      );
    } finally {
      this.rebuild();
      this.resize();
      this.engine.fit();
      this.engine.zoom(before.zoom, this.host.clientWidth / 2, this.host.clientHeight / 2);
      const restored = JSON.parse(this.engine.status());
      this.engine.pan(
        (restored.center[0] - before.center[0]) * restored.scale,
        (before.center[1] - restored.center[1]) * restored.scale
      );
      this.render();
    }
  }

  dispose() {
    this.disposed = true;
    this.abort.abort();
    this.resizeObserver?.disconnect();
    cancelAnimationFrame(this.frame);
    this.imageSizes.clear();
    this.engine?.free();
    this.host.replaceChildren();
  }
}
