"use client";

import { useExtracted } from "next-intl";
import type { TerritoryResourceKind } from "@/autogenerated/container/rokbattles_container";
import type { BuildingKind } from "@/lib/territory-lab/types";

export function useTerritoryLabels() {
  const t = useExtracted();
  const resourceLabels: Record<TerritoryResourceKind, string> = {
    food: t("Food"),
    wood: t("Wood"),
    stone: t("Stone"),
    coin: t("Gold"),
    crystal: t("Crystal"),
  };
  const buildingLabels: Record<BuildingKind, string> = {
    flag: t("Flag"),
    "center-fortress": t("Center Fortress"),
    fortress: t("Fortress"),
    horse: t("Horse"),
  };
  return {
    resourceLabel: (kind: TerritoryResourceKind) => resourceLabels[kind],
    buildingLabel: (kind: BuildingKind) => buildingLabels[kind],
  };
}
