[package]
name = "rokbattles-api"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "json", "query", "tokio", "tracing"] }
base64 = { workspace = true }
dotenvy = { workspace = true }
futures = { workspace = true, features = ["std"] }
mongodb = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls-native-roots"] }
rokbattles-bson = { path = "../../common/rokbattles-bson" }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
sentry = { workspace = true, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls"] }
yaml_serde = { workspace = true }

[target.'cfg(all(target_os = "linux", target_env = "musl"))'.dependencies]
mimalloc = { workspace = true, features = ["secure"] }

[lib]
doctest = false

[lints]
workspace = true
