[package]
name = "rokbattles-mail-processor-alliance-aoo-registration"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rokbattles-mail-sdk = { path = "../rokbattles-mail-sdk" }
serde_json = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true
