import commandersData from "@/autogenerated/commanders.json";

const commanderMap = commandersData.commanders;

type CommanderIdKey = keyof typeof commanderMap;

export function getCommanderName(id: number | null | undefined): string | undefined {
  if (typeof id !== "number" || !Number.isFinite(id) || id <= 0) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander) {
    return undefined;
  }

  return (commander.name as Record<string, string | undefined>).en ?? commander.name.en;
}
