[package]
name = "rokbattles-jobs"
version = "1.4.0"
edition = "2024"

[dependencies]
dotenvy = { workspace = true }
drastc = { path = "../drastc" }
futures = { workspace = true }
mongodb = { workspace = true }
rokbattles-api = { path = "../rokbattles-api" }
sentry = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }
tokio-cron-scheduler = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lib]
doctest = false
