[package]
name = "mail-cli"
version = "1.6.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
mail-decoder = { path = "../decoder" }
mail-registry = { path = "../registry", features = ["processors"] }
mail-sdk = { path = "../sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false
