#!/bin/sh
set -eu

# Keep the CLI and crate versions in sync; wasm-bindgen's output ABI must match.
workspace_dir=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)
cd "$workspace_dir"
bindgen_version=$(sed -n 's/^wasm-bindgen = "=\([^"]*\)"$/\1/p' Cargo.toml)
[ -n "$bindgen_version" ] || { echo 'Expected an exact workspace wasm-bindgen version' >&2; exit 1; }
if [ "$(wasm-bindgen --version 2>/dev/null || true)" != "wasm-bindgen $bindgen_version" ]; then
    cargo install wasm-bindgen-cli --version "$bindgen_version" --locked
fi
rustup target add wasm32-unknown-unknown
cargo build -p rokbattles-container --target wasm32-unknown-unknown \
    --no-default-features --features wasm-read --release --locked
wasm_output_dir=${CONTAINER_WASM_OUT_DIR:-$workspace_dir/packages/site/src/autogenerated/container}
wasm_target_dir=${CARGO_TARGET_DIR:-$workspace_dir/target}
wasm-bindgen "$wasm_target_dir/wasm32-unknown-unknown/release/rokbattles_container.wasm" \
    --target web --out-dir "$wasm_output_dir" --out-name rokbattles_container
