#!/bin/sh
set -eu

# Keep the CLI and crate versions in sync; wasm-bindgen's output ABI must match.
workspace_dir=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)
cd "$workspace_dir"
bindgen_version=$(sh "$workspace_dir/packages/site/scripts/wasm-bindgen-version.sh")
if [ "$(wasm-bindgen --version 2>/dev/null || true)" != "wasm-bindgen $bindgen_version" ]; then
    cargo install wasm-bindgen-cli --version "$bindgen_version" --locked
fi
rustup target add wasm32-unknown-unknown
cargo build -p rokbattles-container --target wasm32-unknown-unknown \
    --no-default-features --features wasm-read --profile size --locked
wasm_output_dir=${CONTAINER_WASM_OUT_DIR:-$workspace_dir/packages/site/src/autogenerated/container}
wasm_target_dir=${CARGO_TARGET_DIR:-$workspace_dir/target}
wasm-bindgen "$wasm_target_dir/wasm32-unknown-unknown/size/rokbattles_container.wasm" \
    --target web --out-dir "$wasm_output_dir" --out-name rokbattles_container
