#!/bin/sh
# Build the browser map engine and regenerate its JavaScript/TypeScript bindings.
# Run from any directory. Requires wasm32-unknown-unknown and wasm-bindgen-cli;
# MAP_ENGINE_WASM_OUT_DIR overrides packages/site/src/autogenerated/map-engine.
set -eu

workspace_dir=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)
cd "$workspace_dir"

# The CLI and Rust crate must agree on wasm-bindgen's generated binding format.
# Read the workspace pin so dependency updates have a single source of truth.
expected=$(sed -n 's/^wasm-bindgen = "=\([^"]*\)"$/\1/p' Cargo.toml)
if [ "$(wasm-bindgen --version)" != "wasm-bindgen $expected" ]; then
    echo "Install wasm-bindgen-cli $expected to match the workspace." >&2
    exit 1
fi

# Compile only the library, one job at a time, using the workspace's WASM profile.
cargo build -p rokbattles-webgpu-map-engine --target wasm32-unknown-unknown --profile size --lib --locked -j 1

# Cargo may use a caller-supplied target directory; bind the module from that build.
wasm_target_dir=${CARGO_TARGET_DIR:-$workspace_dir/target}
wasm_output_dir=${MAP_ENGINE_WASM_OUT_DIR:-$workspace_dir/packages/site/src/autogenerated/map-engine}
wasm-bindgen "$wasm_target_dir/wasm32-unknown-unknown/size/rokbattles_webgpu_map_engine.wasm" --target web --out-dir "$wasm_output_dir" --out-name rokbattles_webgpu_map_engine

# Fast Refresh can classify WebGL's useProgram call as a React hook in generated
# worker bindings. Computed property access preserves the call while avoiding
# that transform. Apply this after generation because wasm-bindgen rewrites the file.
node --input-type=module - "$wasm_output_dir/rokbattles_webgpu_map_engine.js" <<'JS'
import { readFileSync, writeFileSync } from "node:fs";
const path = process.argv[2];
writeFileSync(path, readFileSync(path, "utf8").replaceAll(".useProgram(", '["useProgram"]('));
JS
