[package]
name = "core-tcp-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
core-tcp-stream = { path = "../core-tcp-stream" }
dotenvy = { workspace = true }
flate2 = { workspace = true, features = ["zlib-rs"] }
futures = { workspace = true }
mongodb = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
