import Image from "next/image";
import type { TerritoryResourceKind } from "@/autogenerated/container/rokbattles_container";
import { RESOURCE_SPRITES } from "@/lib/territory/assets";

export function ResourceIcon({ kind }: { kind: TerritoryResourceKind | "credits" }) {
  return (
    <Image
      alt=""
      aria-hidden="true"
      className="size-5 shrink-0 object-contain"
      height={20}
      src={RESOURCE_SPRITES[kind]}
      width={20}
    />
  );
}
