//! Localized mail body templates from `samples/game/mail`.

pub(crate) const BODY_TEMPLATES: &[&str] = &[
    // BARBARIAN_CONTENT_2
    "تهانينا! لقد تم تدمير الحصن البربري من المستوى {p2} في {p1} بواسطة هجومك العظيم.\n\nلقد تعاملت {p3} مع مجموع الأضرار وكنتيجة لذلك تلقيت <color=#00980e> المكافآت {p4} </color> التالية:",
    "执政官！位于{p1}的等级{p2}野蛮人城寨在您的猛攻之下已经被摧毁，您在这次战役中总共造成了{p3}的伤害，因此获得了<color=#00980e>{p4}阶</color>的战利品：",
    "Herzlichen Glückwunsch! Die Level {p2} Barbarenfestung bei {p1} wurde durch Deinen mächten Angriff zerstört.\nDu hast {p3} des Gesamtschadens verursacht und erhältst deshalb die folgenden <color=#00980e>Klasse {p4}</color> Trophäen:\n",
    "Congratulations! The Level {p2} barbarian fort at {p1} has been destroyed by your mighty onslaught.\n\nYou dealt {p3} of the total damage and as a result have received the following <color=#00980e>Tier {p4}</color> trophies:",
    "¡Felicitaciones! Tu embestida poderosa destruyó el Fuerte bárbaro de nivel {p2} en {p1}.\nProvocaste {p3} del daño total y, por lo tanto, recibiste los siguientes trofeos de <color=#00980e>nivel {p4}</color>:\n",
    "Félicitations !\n\nLe fort barbare niveau  à  a été détruit par votre puissant assaut. Vous avez infligé {p3} des dégâts totaux et avez donc reçu les trophées de <color=#00980e>niveau {p4}</color> suivants :",
    "Selamat! Barbarian Fort Level {p2} di {p1} telah dihancurkan oleh kekuatanmu.\nKamu memberikan {p3} dari damage total sehingga menerima tropi <color=#00980e>rank {p4}</color> berikut:",
    "Congratulazioni! Il forte barbaro di livello {p2} a {p1} è stato distrutto dal tuo possente attacco violento.\nHai arrecato {p3} punti del danno totale, per cui ricevi i trofei del seguente <color=#00980e>rango {p4}</color>:",
    "総督！{p1}に位置する野蛮人の集落Lv.{p2}があなたの猛攻によって破壊されました。今回の戦いであなたは{p3}のダメージを与え、<color=#00980e>レベル{p4}の</color>戦利品を獲得しました。",
    "지도자님! 맹공을 퍼부은 끝에 {p1}에 위치한 {p2}레벨 야만인 도시를 파괴했습니다. 이번 전투 중 총 {p3}의 피해를 입혀 <color=#00980e>{p4}레벨의 </color>전리품을 획득했습니다.",
    "Tahniah! Kubu Orang Gasar Tahap {p2} di {p1} telah dimusnahkan oleh serangan hebat anda yang kuat.\nAnda telah menangani {p3} daripada jumlah kerosakan dan dengan itu, telah menerima trofi <color=#00980e>Tingkat {p4}</color> berikut:\n",
    "Gratulacje! W wyniku waszego potężnego ataku zniszczony został fort barbarzyńców na poz. {p2} w: {p1}.\n\nUdało ci się zadać {p3} z sumy obrażeń, dzięki czemu otrzymujesz poniższe trofea <color=#00980e>poziomu {p4}</color>:",
    "Parabéns! O Nível {p2} Forte Bárbaro em {p1} foi destruído pelo seu poderoso ataque.\nVocê causou {p3} do dano total e, portanto, recebeu os seguintes troféus <color=#00980e> TIpo {p4}</color>:\n",
    "Поздравляем! Форт варваров уровня {p2} рядом с {p1} был уничтожен вашим неудержимым натиском.\n\nВы нанесли {p3} всего урона и получили следующие трофеи <color=#00980e>{p4} уровня</color>:",
    "ยินดีด้วย! ป้อมคนเถื่อนเลเวล {p2} ที่ {p1} ถูกทำลายโดยกองกำลังอันเกรียงไกรของคุณ\nคุณสร้างความเสียหาย {p3} จากทั้งหมดจึงได้รับรางวัลประจำ<color=#00980e>ชั้น {p4}</color>ต่อไปนี้:\n:",
    "Tebrikler! {p1} konumundaki {p2}. Seviye barbar kalesi şiddetli saldırın sayesinde yok edildi.\n\nToplam hasarın {p3} kısmını verdiğin için aşağıdaki <color=#00980e>Katman {p4}</color> ödüllerini aldın:",
    "Xin chúc mừng! Pháo đài Barbaria cấp {p2} ở {p1} đã bị tiêu diệt trong cuộc thảm sát hùng mạnh của bạn.\nBạn đã gây {p3} trong tổng số sát thương và do đó nhận được các chiến lợi phẩm <color=#00980e>cấp {p4}</color> sau đây:\n\n",
    "執政官！位於{p1}的等級{p2}野蠻人城寨在您的猛攻下已被摧毀，您在這次戰役中總共造成{p3}的傷害，因此獲得<color=#00980e>{p4}階</color>的戰利品：",
    // BARBARIAN_CONTENT_3
    "تهانينا! تم تدمير {p2} في {p1} بسبب هجومك العظيم. لقد أحدثت {p3} اجمالي الأضرار ونتيجة لذلك تلقيت <color=#00980e> جوائز Tier {p4} </color> التالية:",
    "执政官！位于{p1}的{p2}在您的猛攻之下已经被摧毁，您在这次战役中总共造成了{p3}的伤害，因此获得了<color=#00980e>{p4}阶</color>的战利品：",
    "Herzlichen Glückwunsch! {p2} bei {p1} wurden durch deinen mächtigen Angriff zerstört. Du hast {p3} des Gesamtschadens verursacht und erhältst deshalb die folgenden <color=#00980e>Klasse{p4}</color> Trophäen:",
    "Congratulations! The {p2} at {p1} has been destroyed by your mighty onslaught. You dealt {p3} of the total damage and as a result have received the following <color=#00980e>Tier {p4}</color> trophies:",
    "¡Felicitaciones! El/la {p2} en {p1} ha sido destruido(a) por tu poderoso ataque. Provocaste {p3} del daño total y como resultado, has recibido los siguientes <color=#00980e> trofeos de nivel {p4}</color>:",
    "Félicitations ! Le fort barbare niveau {p2} à {p1} a été détruit par votre puissant assaut. Vous avez infligé {p3} des dégâts totaux et avez donc reçu les trophées de <color=#00980e>niveau {p4}</color> suivants :",
    "Selamat! {p2} di {p1} telah dihancurkan oleh kekuatan besarmu. Kamu memberikan {p3} dari damage total dan hasilnya kamu menerima trofi <color=#00980e> Tingkat {p4}</color> berikut:",
    "Congratulazioni! Il {p2} a {p1} è stato distrutto dal tuo attacco possente. Hai inflitto {p3} del danno totale e di conseguenza hai ricevuto i seguenti trofei di <color=#00980e>livello {p4}</color>:",
    "総督、おめでとうございます！{p1}に位置した{p2}は、あなたの猛攻により破壊されました。今回の戦いで{p3}のダメージを与え、<color=#00980e>{p4}ランク</color>の戦利品を獲得しました。",
    "지도자님, 축하드립니다! 지도자님의 맹공으로 {p1}에 위치한 {p2}의 파괴에 성공했습니다. 이번 전투 중 총 {p3}의 피해를 입혀 <color=#00980e>{p4}</color>급 전리품을 획득했습니다.",
    "Syabas! {p2} di {p1} telah dimusnahkan oleh serangan anda yang begitu dahsyat sekali. Anda telah mengakibatkan {p3} daripada jumlah kerosakan dan dengan itu, telah menerima trofi <color=#00980e>Tingkat {p4}</color> berikut:",
    "Gratulacje! W wyniku waszego potężnego ataku zniszczono: {p2} ({p1}). Udało ci się zadać {p3} z sumy obrażeń, dzięki czemu otrzymujesz poniższe trofea <color=#00980e>poziomu {p4}</color>:",
    "Parabéns! O {p2} em {p1} foi destruído pelo seu poderoso ataque. Você causou {p3} do dano total e, portanto, recebeu os seguintes troféus da seguinte <color=#00980e>Camada {p4}</color>:",
    "Поздравляем! Вы неудержимым натиском уничтожили {p2} рядом с {p1}. Вы нанесли {p3} всего урона и получили следующие трофеи <color=#00980e>{p4} уровня</color>:",
    "ยินดีด้วย! {p2} ที่ {p1} ถูกทำลายโดยกองกำลังอันเกรียงไกรของคุณแล้ว คุณได้สร้างความเสียหาย {p3} จากความเสียหายทั้งหมด จึงได้รับรางวัลประจำ<color=#00980e>ขั้น {p4}</color> ดังต่อไปนี้:",
    "Tebrikler! {p1} konumundaki {p2} noktası, şiddetli saldırın sayesinde yok edildi. Toplam hasarın {p3} oranı senin tarafından verildi ve bunun sonucu olarak aşağıdaki <color=#00980e>Katman {p4}</color> ödüllerini aldın:",
    "Xin chúc mừng! {p2} ở {p1} đã bị tiêu diệt trong cuộc thảm sát hùng mạnh của bạn. Bạn đã gây {p3} trong tổng số sát thương và do đó nhận được các chiến lợi phẩm <color=#00980e>cấp {p4}</color> sau đây:",
    "執政官！位於{p1}的{p2}在您的猛攻之下已經被摧毀，您在這次戰役中總共造成了{p3}的傷害，因此獲得了<color=#00980e>{p4}階</color>的戰利品：",
    // BARBARIAN_CONTENT_2_S10
    "تهانينا! لقد دُمّرت قلعة موتي من المستوى {p2} في {p1} بسبب هجومك العظيم. لقد تسببت في {p3} من الضرر الإجمالي ونتيجةً لذلك تلقيت نهب من <color=#00980e>المستوى {p4}</color>:",
    "执政官！位于{p1}的等级{p2}炮塔门楼在您的猛攻之下已经被摧毁，您在这次战役中总共造成了{p3}的伤害，因此获得了<color=#00980e>{p4}阶</color>的战利品：",
    "Herzlichen Glückwunsch! Die Lv.-{p2}-Motte in „{p1}“ wurde durch deinen mächtigen Angriff zerstört. Du hast {p3} des Gesamtschadens verursacht und erhältst deshalb die folgende <color=#00980e>Lv.-{p4}</color>-Beute:",
    "Congratulations! The level {p2} Motte at {p1} has been destroyed by your mighty onslaught. You dealt {p3} of the total damage and as a result received <color=#00980e>level {p4}</color> plunder:",
    "¡Felicitaciones! Tu feroz ataque destruyó la mota de nivel {p2} que estaba en {p1}. Provocaste {p3} del daño total y, como resultado, recibiste el siguiente botín de <color=#00980e>nivel {p4}</color>:",
    "Félicitations ! La motte de niveau {p2} à {p1} a été détruite par votre puissant assaut. Vous avez infligé {p3} des dégâts totaux et avez reçu un <color=#00980e>butin de niveau {p4}</color> :",
    "Selamat! Bukit level {p2} di {p1} telah dihancurkan oleh serangan besarmu. Kamu menimpakan {p3} dari damage total dan sebagai hasilnya kamu menerima jarahan <color=#00980e>level {p4}</color> berikut:",
    "Congratulazioni! La motta di livello {p2} collocata a {p1} è stata distrutta dal tuo attacco possente. Hai inflitto {p3} del danno totale e di conseguenza hai ricevuto il bottino di <color=#00980e>livello {p4}</color>:",
    "総督！{p1}に位置するモット城郭Lv.{p2}があなたの猛攻によって破壊されました。今回の戦いであなたは{p3}のダメージを与え、<color=#00980e>レベル{p4}の</color>戦利品を獲得しました。",
    "지도자님! 맹공을 퍼부은 끝에 {p1}에 위치한 {p2}레벨 포탑 문루를 파괴했습니다.이번 전투에서 총 {p3}의 피해를 입혀 <color=#00980e>{p4}레벨의 </color>전리품을 획득했습니다.",
    "Tahniah! Motte tahap {p2} di {p1} telah dimusnahkan oleh serangan hebat anda. Anda telah menyebabkan {p3} daripada jumlah kerosakan dan hasilnya menerima rampasan <color=#00980e>tahap {p4}</color>:",
    "Gratulacje! W wyniku waszego potężnego ataku zniszczony został Gród na poz. {p2} ({p1}). Udało ci się zadać {p3} z sumy obrażeń, dzięki czemu otrzymujesz poniższe łupy <color=#00980e>poziomu {p4}</color>:",
    "Parabéns! A Mota de nível {p2} em {p1} foi destruída por seu poderoso ataque. Você causou {p3} do dano total e, como resultado, recebeu pilhagem de <color=#00980e>nível{p4}</color>:",
    "Поздравляем! Вы неудержимым натиском уничтожили мотт ур. {p2} рядом с {p1}. Вы нанесли {p3} всего урона и получили трофей <color=#00980e>{p4} уровня</color>:",
    "ยินดีด้วย! ปราสาทเนินเลเวล {p2} ที่ {p1} ถูกทำลายโดยกองกำลังอันเกรียงไกรของคุณแล้ว คุณได้สร้างความเสียหาย {p3} จากความเสียหายทั้งหมด จึงได้รับการปล้นสะดม<color=#00980e>เลเวล {p4}</color>",
    "Tebrikler! {p1} konumundaki {p2}. seviye Motte, şiddetli saldırın sayesinde yok edildi. Toplam hasarın {p3} oranı senin tarafından verildi ve bunun sonucu olarak <color=#00980e>{p4}. seviye</color> ganimet aldın:",
    "Xin chúc mừng! Tháp Pháo cấp {p2} ở {p1} đã bị phá hủy trong đợt tấn công mãnh liệt của ngài. Ngài gây ra tổng cộng {p3} sát thương và do đó nhận được chiến lợi phẩm <color=#00980e>cấp {p4}</color>:",
    "執政官！位於{p1}的等級{p2}砲塔門樓已在您的猛攻之下被摧毀，您在這次戰役中，共造成了{p3}的傷害，因此獲得了<color=#00980e>{p4}階</color>的戰利品：",
];
