[package]
name = "rokbattles-capture-adapters"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos", all(windows, any(target_arch = "x86", target_arch = "x86_64"))))'.dependencies]
libloading = "0.8.9"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc.workspace = true

[lints]
workspace = true
