import commandersData from "@/autogenerated/commanders.json";
import { defaultLocale, isLocale, type Locale } from "@/i18n/config";
import { getGameSpriteUrl, getGameSpriteUrls } from "@/lib/game-sprite";

export const commanderMap = commandersData.commanders;

type CommanderSkillEntry = {
  slot?: number;
  id?: number;
  expertId?: number;
  sprite?: string | string[];
  expertSprite?: string | string[];
};

type CommanderCatalogEntry = {
  name: Record<string, string | undefined>;
  rarity?: string;
  sprite?: string | string[];
  skills?: CommanderSkillEntry[];
};

type CommanderSkillLevel = {
  id?: number | null;
  level?: number | null;
};

export type CommanderSkillDisplay = {
  id: number;
  level?: number;
  spriteUrls: string[];
  expert: boolean;
};

const commanderCatalog = commanderMap as Record<string, CommanderCatalogEntry | undefined>;

type CommanderIdKey = keyof typeof commanderMap;
type CommanderEntry = (typeof commanderMap)[CommanderIdKey];
type CommanderLocale = keyof CommanderEntry["name"];

export function resolveCommanderLocale(locale?: string): Locale {
  if (locale && isLocale(locale)) {
    return locale;
  }

  return defaultLocale;
}

export function getCommanderName(id: number | null | undefined, locale?: string) {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander) {
    return undefined;
  }

  const resolvedLocale = resolveCommanderLocale(locale);
  return (
    (commander.name as Record<string, string | undefined>)[resolvedLocale] ??
    commander.name[defaultLocale as CommanderLocale]
  );
}

export function getCommanderSprites(
  id: number | null | undefined,
  awakened = false
): string[] | undefined {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  const commander = commanderMap[String(id) as CommanderIdKey];
  if (!commander?.sprite) {
    return undefined;
  }

  const sprites = Array.isArray(commander.sprite) ? commander.sprite : [commander.sprite];

  return sprites
    .filter((sprite): sprite is string => typeof sprite === "string" && sprite.length > 0)
    .map((sprite, index) => {
      if (!awakened || index !== 0) {
        return sprite;
      }

      if (commander.rarity === "epic") {
        return "img_icon_HeroProfile_BGMask_pink.png";
      }

      if (commander.rarity === "legendary") {
        return "img_icon_HeroProfile_BGMask_Orange.png";
      }

      return sprite;
    })
    .map(getGameSpriteUrl);
}

export function getCommanderSkillDisplays(
  commanderId: number | null | undefined,
  reportSkills: readonly CommanderSkillLevel[] | null | undefined,
  awakened?: boolean | null
): CommanderSkillDisplay[] {
  const entries = getCommanderSkillEntries(commanderId);
  if (entries.length === 0) {
    return [];
  }

  const reportSkillById = new Map<number, CommanderSkillLevel>();
  for (const skill of reportSkills ?? []) {
    const id = skill.id;
    if (typeof id === "number" && Number.isFinite(id) && id > 0) {
      reportSkillById.set(id, skill);
    }
  }

  const displays: CommanderSkillDisplay[] = [];
  const standardEntries = entries.filter((entry) => entry.slot !== 5);

  for (const entry of standardEntries) {
    if (!isFinitePositiveNumber(entry.id)) {
      continue;
    }

    const expertOverrideActive =
      isFinitePositiveNumber(entry.expertId) &&
      (reportSkillById.has(entry.expertId) || awakened === true);
    const level =
      getSkillLevel(reportSkillById.get(entry.id)) ?? (expertOverrideActive ? 5 : undefined);
    const spriteUrls = getGameSpriteUrls(entry.sprite);

    if (spriteUrls.length > 0) {
      displays.push({
        id: entry.id,
        level,
        spriteUrls,
        expert: false,
      });
    }
  }

  const expertDisplays = entries
    .filter((entry) => {
      if (entry.slot === 5 && isFinitePositiveNumber(entry.id)) {
        return reportSkillById.has(entry.id) || awakened === true;
      }

      return (
        isFinitePositiveNumber(entry.expertId) &&
        (reportSkillById.has(entry.expertId) || awakened === true)
      );
    })
    .map((entry): CommanderSkillDisplay | null => {
      const expertId = entry.slot === 5 ? entry.id : entry.expertId;
      if (!isFinitePositiveNumber(expertId)) {
        return null;
      }

      const spriteUrls = getGameSpriteUrls(entry.slot === 5 ? entry.sprite : entry.expertSprite);
      if (spriteUrls.length === 0) {
        return null;
      }

      return {
        id: expertId,
        spriteUrls,
        expert: true,
      };
    })
    .filter((display): display is CommanderSkillDisplay => display != null);

  return [...displays, ...expertDisplays];
}

export function getCommanderSkillSpriteUrls(
  commanderId: number | null | undefined,
  skillId: number | null | undefined
): string[] {
  const entry =
    findCommanderSkillEntry(commanderId, skillId) ?? findAnyCommanderSkillEntry(skillId);
  if (!entry) {
    return [];
  }

  const sprites = entry.expertId === skillId ? entry.expertSprite : entry.sprite;
  return getGameSpriteUrls(sprites);
}

function getCommanderSkillEntries(commanderId: number | null | undefined): CommanderSkillEntry[] {
  if (typeof commanderId !== "number" || !Number.isFinite(commanderId)) {
    return [];
  }

  return [...(commanderCatalog[String(commanderId)]?.skills ?? [])].sort(
    (a, b) => (a.slot ?? 0) - (b.slot ?? 0)
  );
}

function findCommanderSkillEntry(
  commanderId: number | null | undefined,
  skillId: number | null | undefined
): CommanderSkillEntry | undefined {
  if (!isFinitePositiveNumber(skillId)) {
    return undefined;
  }

  return getCommanderSkillEntries(commanderId).find(
    (entry) => entry.id === skillId || entry.expertId === skillId
  );
}

function findAnyCommanderSkillEntry(
  skillId: number | null | undefined
): CommanderSkillEntry | undefined {
  if (!isFinitePositiveNumber(skillId)) {
    return undefined;
  }

  for (const commander of Object.values(commanderCatalog)) {
    const entry = commander?.skills?.find(
      (skill) => skill.id === skillId || skill.expertId === skillId
    );
    if (entry) {
      return entry;
    }
  }

  return undefined;
}

function getSkillLevel(skill: CommanderSkillLevel | undefined): number | undefined {
  return isFinitePositiveNumber(skill?.level) ? skill.level : undefined;
}

function isFinitePositiveNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value > 0;
}
