let initialization:
  | Promise<typeof import("@/autogenerated/container/rokbattles_container")>
  | undefined;

function loadContainer() {
  initialization ??= import("@/autogenerated/container/rokbattles_container")
    .then(async (module) => {
      await module.default();
      return module;
    })
    .catch((error: unknown) => {
      initialization = undefined;
      throw error;
    });
  return initialization;
}

/** Validates a container in Rust and returns bytes for an application schema decoder. */
export async function readContainerPayload(
  buffer: ArrayBuffer,
  schemaId: number
): Promise<Uint8Array> {
  const { Reader } = await loadContainer();
  const reader = new Reader();
  try {
    const decoded = reader.readEnvelope(new Uint8Array(buffer), schemaId);
    try {
      const payload = decoded.value;
      if (!(payload instanceof Uint8Array)) throw new Error("Expected a byte payload");
      return payload;
    } finally {
      decoded.free();
    }
  } finally {
    reader.free();
  }
}
