import type { SchemaId, SchemaValues } from "@/autogenerated/container/rokbattles_container";

let initialization:
  | Promise<typeof import("@/autogenerated/container/rokbattles_container")>
  | undefined;

function loadContainer() {
  initialization ??= import("@/autogenerated/container/rokbattles_container")
    .then(async (module) => {
      await module.default();
      return module;
    })
    .catch((error: unknown) => {
      initialization = undefined;
      throw error;
    });
  return initialization;
}

/** Validates and decodes the selected schema in Rust. */
export async function decodeContainer<S extends SchemaId>(
  buffer: ArrayBuffer,
  schemaId: S
): Promise<SchemaValues[S]> {
  const { Reader } = await loadContainer();
  const reader = new Reader();
  try {
    const decoded = reader.decode(new Uint8Array(buffer), schemaId);
    try {
      return decoded.value;
    } finally {
      decoded.free();
    }
  } finally {
    reader.free();
  }
}
