import equipmentData from "@/autogenerated/equipment.json";

export type EquipmentTroopType =
  | "infantry"
  | "archer"
  | "cavalry"
  | "integration"
  | "leadership"
  | "engineering";

const TROOP_TYPE_ICON_PATHS: Record<EquipmentTroopType, string> = {
  infantry: "btn_BlackSmithsShopSystemInfantry.png",
  archer: "btn_BlackSmithsShopSystemArcher.png",
  cavalry: "btn_BlackSmithsShopSystemCavalry.png",
  integration: "btn_BlackSmithsShopSystemIntegration.png",
  leadership: "btn_BlackSmithsShopSystemLeadership.png",
  engineering: "btn_BlackSmithsShopSystemVehicle.png",
};

const ATTR_TROOP_TYPE_MAP: Record<number, EquipmentTroopType> = {
  1: "infantry",
  2: "archer",
  3: "cavalry",
  4: "integration",
  5: "leadership",
  16: "engineering",
};

const equipmentMap = equipmentData.equipment.item;

type EquipmentIdKey = keyof typeof equipmentMap;
type EquipmentEntry = (typeof equipmentMap)[EquipmentIdKey];

function getEquipmentEntry(id: number | null | undefined): EquipmentEntry | undefined {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  return equipmentMap[String(id) as EquipmentIdKey] as EquipmentEntry | undefined;
}

export function getEquipmentTierInfo(attr?: number) {
  if (typeof attr !== "number" || !Number.isFinite(attr)) {
    return { tier: undefined, isSpecialTalent: false, troopType: undefined };
  }

  const numeric = Number(attr);
  const troopTypeCode = Math.floor(numeric / 10);
  const troopType = ATTR_TROOP_TYPE_MAP[troopTypeCode];
  const isSpecialTalent = troopType != null;
  const base = isSpecialTalent ? numeric % 10 : numeric;
  const tier = Number.isFinite(base) ? base : undefined;

  return { tier, isSpecialTalent, troopType };
}

export function getEquipmentTroopTypeIconSrc(troopType?: EquipmentTroopType) {
  if (!troopType) {
    return undefined;
  }

  return `https://cdn.rokbattles.com/game/sprites/${TROOP_TYPE_ICON_PATHS[troopType]}`;
}

export function getEquipmentSpriteUrl(id: number | null | undefined): string | undefined {
  const equipment = getEquipmentEntry(id);
  const sprite = Array.isArray(equipment?.sprite) ? equipment.sprite[0] : equipment?.sprite;

  if (typeof sprite !== "string" || sprite.length === 0) {
    return undefined;
  }

  return `https://cdn.rokbattles.com/game/sprites/${sprite}`;
}

export function toRomanNumeral(value: number | undefined) {
  if (typeof value !== "number") {
    return null;
  }

  const numerals = ["", "I", "II", "III", "IV", "V"];
  return numerals[value] ?? null;
}
