import commandersData from "@/autogenerated/commanders.json";

export type OverlayCommander = {
  name: string;
  sprites: string[];
  rarity: string;
};

export function getOverlayCommanders(): Record<string, OverlayCommander> {
  return Object.fromEntries(
    Object.entries(commandersData.commanders).map(([id, commander]) => [
      id,
      {
        name: `${commander.name.en}${commander.prime ? " (Prime)" : ""}`,
        sprites: commander.sprite,
        rarity: commander.rarity,
      },
    ])
  );
}
