import relicsData from "@/autogenerated/relics.json";
import { defaultLocale, isLocale } from "@/i18n/config";
import { getGameSpriteUrls } from "@/lib/game-sprite";

type RelicCatalogEntry = {
  name: Record<string, string | undefined>;
  sprite?: string | string[];
};

type RelicCatalog = Record<string, RelicCatalogEntry>;

const relicCatalog = relicsData.relics as RelicCatalog;

function resolveLocale(locale?: string): string {
  return isLocale(locale) ? locale : defaultLocale;
}

export function getRelicLevelFromId(id: number | null | undefined): number | undefined {
  if (typeof id !== "number" || !Number.isFinite(id) || id <= 0) {
    return undefined;
  }

  if (id >= 20000) {
    return 3;
  }

  if (id >= 10000) {
    return 2;
  }

  return 1;
}

export function getRelicName(id: number | null | undefined, locale?: string): string | undefined {
  const relic = getRelicEntry(id);
  if (!relic) {
    return undefined;
  }

  const targetLocale = resolveLocale(locale);
  return relic.name[targetLocale] ?? relic.name[defaultLocale];
}

export function getRelicSpriteUrls(id: number | null | undefined): string[] | undefined {
  const relic = getRelicEntry(id);
  if (!relic?.sprite) {
    return undefined;
  }

  return getGameSpriteUrls(relic.sprite);
}

function getRelicEntry(id: number | null | undefined): RelicCatalogEntry | undefined {
  if (typeof id !== "number" || !Number.isFinite(id)) {
    return undefined;
  }

  return relicCatalog[String(id)] ?? relicCatalog[String(getBaseRelicId(id))];
}

function getBaseRelicId(id: number): number {
  return id >= 10000 ? id % 10000 : id;
}
