[package]
name = "rokbattles-processor"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
mongodb = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
futures = { workspace = true, features = ["std"] }
zstd = { workspace = true }
sha2 = { workspace = true }
dotenvy = { workspace = true }
rokbattles-mail-decoder = { path = "../../common/rokbattles-mail-decoder" }
rokbattles-mail-registry = { path = "../../common/rokbattles-mail-registry", features = ["processors"] }
rokbattles-mail-sdk = { path = "../../common/rokbattles-mail-sdk" }
sentry = { workspace = true, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls"] }

[target.'cfg(all(target_os = "linux", target_env = "musl"))'.dependencies]
mimalloc = { workspace = true, features = ["secure"] }
