import init, { Reader } from "@/autogenerated/container/rokbattles_container";
import type { Catalog, MapData, Mode, Site } from "./types";
import { CDN } from "./types";

let initialized: Promise<unknown> | undefined;
const MAX_DATASET_BYTES = 8 * 1024 * 1024;

/** Reads a catalog-pinned response without allowing a compromised origin to force an unbounded allocation. */
export async function readVerifiedDataset(
  response: Response,
  expected: { sha256: string; bytes: number }
): Promise<Uint8Array> {
  if (
    !Number.isSafeInteger(expected.bytes) ||
    expected.bytes <= 0 ||
    expected.bytes > MAX_DATASET_BYTES ||
    !/^[a-f\d]{64}$/u.test(expected.sha256)
  )
    throw new Error("Invalid dataset metadata.");
  const declared = response.headers.get("content-length");
  if (declared !== null && Number(declared) !== expected.bytes)
    throw new Error("The dataset size does not match the catalog.");
  if (!response.body) throw new Error("The dataset response has no body.");

  const output = new Uint8Array(expected.bytes);
  const reader = response.body.getReader();
  let offset = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (offset + value.byteLength > output.byteLength)
        throw new Error("The dataset exceeds its catalog size.");
      output.set(value, offset);
      offset += value.byteLength;
    }
  } catch (error) {
    await reader.cancel().catch(() => undefined);
    throw error;
  } finally {
    reader.releaseLock();
  }
  if (offset !== output.byteLength) throw new Error("The dataset is truncated.");
  const hash = new Uint8Array(await crypto.subtle.digest("SHA-256", output));
  const digest = Array.from(hash, (n) => n.toString(16).padStart(2, "0")).join("");
  if (digest !== expected.sha256) throw new Error("The dataset digest does not match the catalog.");
  return output;
}

/** Final bins use the generic JSON schema; preserve floats and normalize its BigInts. */
export async function loadMapData(
  catalog: Catalog,
  mode: Mode,
  signal: AbortSignal
): Promise<MapData> {
  initialized ??= init();
  await initialized;
  const reader = new Reader();
  const data: MapData = {
    sites: [],
    landmarks: [],
    resources: [],
    definitions: [],
    instances: [],
    province: null,
    forbiddenBytes: new Uint8Array(),
  };
  try {
    // Decode sequentially to cap the peak allocation of the forbidden mesh.
    for (const category of catalog.categories) {
      if (category === "canyons" && mode !== "baulur") continue;
      if ((category === "caves" || category === "villages") && mode !== "territory") continue;
      if (
        ![
          "structures",
          "canyons",
          "forbidden",
          "rss",
          "province",
          "bastions",
          "caves",
          "villages",
        ].includes(category)
      )
        continue;
      const response = await fetch(
        `${CDN}/${encodeURIComponent(catalog.map)}/${encodeURIComponent(category)}.bin`,
        { signal }
      );
      if (!response.ok) throw new Error(`Could not load ${category} (${response.status}).`);
      const expected = catalog.assets[`${category}.bin`];
      if (!expected) throw new Error(`The ${category} file is missing catalog metadata.`);
      const bytes = await readVerifiedDataset(response, expected);
      const decoded = reader.decode(bytes, 3);
      try {
        const value = JSON.parse(
          JSON.stringify(decoded.value, (_, v) => (typeof v === "bigint" ? Number(v) : v))
        );
        if (value.gameMap !== catalog.map || value.category !== category)
          throw new Error("Map dataset identity mismatch.");
        if (category === "forbidden") {
          data.definitions = value.definitions;
          data.instances = value.instances;
          data.forbiddenBytes = bytes;
        } else if (category === "rss") data.resources = value.points;
        else if (category === "province")
          data.province = {
            ...value,
            flagBlocked: new Set(value.flagBlocked),
            fortressBlocked: new Set(value.fortressBlocked),
          };
        else
          (category === "caves" || category === "villages" ? data.landmarks : data.sites).push(
            ...value.points.map((p: Omit<Site, "id"> & { id: number }) => ({
              ...p,
              id: `${category}:${p.id}`,
            }))
          );
      } finally {
        decoded.free();
      }
    }
  } finally {
    reader.free();
  }
  return data;
}
