/// <reference lib="webworker" />
import init, { Pathfinder } from "@/autogenerated/map-engine/rokbattles_webgpu_map_engine";
import { orderedRouteSites } from "./routes";
import type { Route, RouteLeg, Site } from "./types";

let pathfinder: Pathfinder | undefined;
let initialization: Promise<void> | undefined;
let sites = new Map<string, Site>();
const cache = new Map<string, Omit<RouteLeg, "routeId" | "from" | "to">>();
const MAX_SITES = 1_000;
const MAX_ROUTES = 5;
const MAX_ROUTE_SITES = 512;
const MAX_CACHE_ENTRIES = 1_024;
const MAX_LEGS = MAX_ROUTES * (MAX_ROUTE_SITES - 1);
const MAX_PATH_POINTS = 8_192;

function validPoint(value: unknown): value is [number, number] {
  return (
    Array.isArray(value) &&
    value.length === 2 &&
    value.every((coordinate) => Number.isFinite(coordinate))
  );
}

function validToken(value: unknown, allowColon = false): value is string {
  if (typeof value !== "string" || value.length === 0 || value.length > 64) return false;
  for (const character of value) {
    const code = character.charCodeAt(0);
    if (
      (code >= 48 && code <= 57) ||
      (code >= 65 && code <= 90) ||
      (code >= 97 && code <= 122) ||
      character === "-" ||
      character === "_" ||
      (allowColon && character === ":")
    )
      continue;
    return false;
  }
  return true;
}

function parseLeg(value: string): Omit<RouteLeg, "routeId" | "from" | "to"> {
  const candidate: unknown = JSON.parse(value);
  if (!candidate || typeof candidate !== "object") throw new Error("Invalid navigation result.");
  const { path, start, end } = candidate as Record<string, unknown>;
  if (
    (path !== null &&
      (!Array.isArray(path) || path.length > MAX_PATH_POINTS || !path.every(validPoint))) ||
    (start !== null && !validPoint(start)) ||
    (end !== null && !validPoint(end))
  )
    throw new Error("Invalid navigation result.");
  return { path, start, end } as Omit<RouteLeg, "routeId" | "from" | "to">;
}

self.onmessage = async (event: MessageEvent) => {
  const message = event.data;
  try {
    if (message.type === "init") {
      const bounds: unknown = message.bounds;
      if (
        !Array.isArray(bounds) ||
        bounds.length !== 4 ||
        !bounds.every(Number.isFinite) ||
        bounds[0] >= bounds[2] ||
        bounds[1] >= bounds[3] ||
        !(message.bytes instanceof Uint8Array) ||
        message.bytes.byteLength === 0 ||
        message.bytes.byteLength > 8 * 1024 * 1024 ||
        !Array.isArray(message.sites) ||
        message.sites.length > MAX_SITES ||
        message.sites.some(
          (site: Site) =>
            !site ||
            !validToken(site.id, true) ||
            !validToken(site.kind) ||
            !Number.isFinite(site.x) ||
            !Number.isFinite(site.y) ||
            site.x < bounds[0] ||
            site.x > bounds[2] ||
            site.y < bounds[1] ||
            site.y > bounds[3]
        ) ||
        new Set(message.sites.map((site: Site) => site.id)).size !== message.sites.length
      )
        throw new Error("Invalid navigation input.");
      initialization = (async () => {
        await init();
        pathfinder?.free();
        pathfinder = new Pathfinder(JSON.stringify(message.bounds), message.bytes);
        sites = new Map(message.sites.map((s: Site) => [s.id, s]));
        cache.clear();
      })();
      await initialization;
      self.postMessage({ type: "ready" });
      return;
    }
    await initialization;
    if (!pathfinder) throw new Error("Navigation is not ready.");
    if (
      !Number.isSafeInteger(message.revision) ||
      message.revision < 0 ||
      !Array.isArray(message.routes) ||
      message.routes.length > MAX_ROUTES
    )
      throw new Error("Invalid routes.");
    const legs: RouteLeg[] = [];
    for (const route of message.routes as Route[]) {
      if (
        !route ||
        !validToken(route.id) ||
        !Array.isArray(route.siteIds) ||
        route.siteIds.length > MAX_ROUTE_SITES ||
        route.siteIds.some((id) => !validToken(id, true) || !sites.has(id)) ||
        new Set(route.siteIds).size !== route.siteIds.length
      )
        throw new Error("Invalid route sites.");
      if (
        !Array.isArray(route.passes) ||
        route.passes.length > 128 ||
        route.passes.some(
          (pass) => !pass || !validToken(pass.siteId, true) || !validToken(pass.allianceId)
        )
      )
        throw new Error("Invalid route passes.");
      const passes = route.passes.map(({ siteId }) => sites.get(siteId));
      const validPasses = passes.filter((site): site is Site => site?.kind === "pass");
      if (validPasses.length !== passes.length) throw new Error("Unknown route pass.");
      pathfinder.set_passes(JSON.stringify(validPasses.map((site) => [site.x, site.y])));
      const passKey = route.passes
        .map(({ siteId }) => siteId)
        .sort()
        .join(",");
      const ids = orderedRouteSites(route);
      for (let i = 1; i < ids.length; i++) {
        const a = sites.get(ids[i - 1]);
        const b = sites.get(ids[i]);
        if (!a || !b) continue;
        const key = `${passKey}/${a.id}/${b.id}`;
        let leg = cache.get(key);
        if (!leg) {
          leg = parseLeg(pathfinder.route(a.x, a.y, b.x, b.y));
          if (leg) {
            if (cache.size >= MAX_CACHE_ENTRIES) {
              const oldest = cache.keys().next().value;
              if (oldest !== undefined) cache.delete(oldest);
            }
            cache.set(key, leg);
          }
        }
        if (leg) {
          if (legs.length >= MAX_LEGS) throw new Error("Too many navigation legs.");
          legs.push({ ...leg, routeId: route.id, from: a.id, to: b.id });
        }
      }
    }
    self.postMessage({ type: "routes", revision: message.revision, legs });
  } catch (error) {
    self.postMessage({
      type: "error",
      message: error instanceof Error ? error.message : String(error),
    });
  }
};
