import type { TerritoryStructure } from "@/autogenerated/container/rokbattles_container";
import { buildingCostBreakdown, calculateCostTotals } from "@/lib/territory-lab/costs";
import {
  boundaryCollision,
  buildingRules,
  buildTerritoryOwnership,
  countCoveredResources,
  hasRequiredTerritoryAvailability,
  isConnectedToAlliance,
  isProvinceRestricted,
  mapStructureCollision,
  plannedBuildingCollision,
  type TerritoryOwnership,
} from "@/lib/territory-lab/geometry";
import { nearbyTerrainInstances } from "./terrain";
import type { Building, Catalog, MapData, Plan } from "./types";

const ownershipCache = new WeakMap<
  Building[],
  { catalog: Catalog; data: MapData; ownership: TerritoryOwnership }
>();

function planOwnership(plan: Plan, catalog: Catalog, data: MapData): TerritoryOwnership {
  const cached = ownershipCache.get(plan.buildings);
  if (cached?.catalog === catalog && cached.data === data) return cached.ownership;
  const ownership = buildTerritoryOwnership(plan.buildings, mapStructures(catalog, data));
  ownershipCache.set(plan.buildings, { catalog, data, ownership });
  return ownership;
}

export function placementError(
  candidate: Building,
  plan: Plan,
  catalog: Catalog,
  data: MapData
): string | null {
  const limit = catalog.buildings[candidate.kind]?.limit ?? 0;

  if (
    plan.buildings.filter((b) => b.kind === candidate.kind && b.allianceId === candidate.allianceId)
      .length >= limit
  )
    return "This alliance has reached the building limit.";

  const radius = buildingRules[candidate.kind].baseClearance;

  if (
    candidate.x - radius < 0 ||
    candidate.y - radius < 0 ||
    candidate.x + radius > catalog.nativeMapSize ||
    candidate.y + radius > catalog.nativeMapSize
  )
    return "Place the building inside the playable map.";

  if (isProvinceRestricted(data.province, candidate.kind, candidate.x, candidate.y))
    return "This province does not allow that building.";

  if (plannedBuildingCollision(candidate, plan.buildings))
    return "Another building occupies this position.";

  if (
    boundaryCollision(
      candidate.x,
      candidate.y,
      radius,
      data.definitions,
      nearbyTerrainInstances(data, candidate.x, candidate.y, radius)
    )
  )
    return "The building overlaps forbidden terrain.";

  const structures = mapStructures(catalog, data);
  if (mapStructureCollision(candidate, structures)) return "The building overlaps a map structure.";

  const ownership = planOwnership(plan, catalog, data);
  if (!isConnectedToAlliance(candidate, ownership))
    return "Connect flags to this alliance’s territory. Start with a fortress.";

  if (!hasRequiredTerritoryAvailability(candidate, ownership))
    return "Too much of this footprint belongs to another alliance.";

  return null;
}

export function territorySummary(plan: Plan, catalog: Catalog, data: MapData, allianceId: string) {
  const buildings = plan.buildings;
  const ownership = planOwnership(plan, catalog, data);
  const covered = countCoveredResources(ownership, data.resources, allianceId);
  const production = Object.fromEntries(
    Object.entries(covered).map(([kind, count]) => [
      kind === "coin" ? "gold" : kind,
      count * (catalog.resourceProductionPerHour[kind === "coin" ? "gold" : kind] ?? 0),
    ])
  );
  return {
    ownership,
    covered,
    production,
    entries: buildingCostBreakdown(buildings, catalog.costs, allianceId),
    costs: calculateCostTotals(buildings, catalog.costs, allianceId),
  };
}

/** Reuse production territory rules with the v2 catalog's verified client footprints. */
export function mapStructures(catalog: Catalog, data: MapData): TerritoryStructure[] {
  return data.sites.flatMap((site, index) => {
    if (site.id.startsWith("canyons:")) return [];
    const rule =
      site.kind === "bastion"
        ? {
            collision: { shape: "territory-square" as const, radiusInCells: 1 },
            territoryRadiusInCells: 1,
            teleportRadiusInCells: null,
            claimable: false,
          }
        : catalog.structureRules?.[String(site.strongholdType)];
    if (!rule) return [];
    return [
      {
        ...rule,
        teleportRadiusInCells: rule.teleportRadiusInCells ?? null,
        id: index + 1,
        strongholdType: site.strongholdType ?? 0,
        kind: site.kind as TerritoryStructure["kind"],
        x: site.x,
        y: site.y,
        label: site.label ?? "Bastion",
      },
    ];
  });
}
