import type { TerritoryStructure } from "@/autogenerated/container/rokbattles_container";
import { buildingCostBreakdown, calculateCostTotals } from "@/lib/territory/costs";
import {
  boundaryCollision,
  buildingRules,
  buildTerritoryOwnership,
  countCoveredResources,
  hasRequiredTerritoryAvailability,
  isConnectedToAlliance,
  isProvinceRestricted,
  mapStructureCollision,
  plannedBuildingCollision,
} from "@/lib/territory/geometry";
import type { BuildingCostSchedule, PlannedBuilding } from "@/lib/territory/types";
import type { Building, BuildingKind, Catalog, MapData, Plan } from "./types";

const legacyKinds = {
  flag: "flag",
  "center-fortress": "mainFortress",
  fortress: "subFortress",
  horse: "horse",
} as const;
export function legacyBuilding(building: Building): PlannedBuilding {
  return { ...building, kind: legacyKinds[building.kind] };
}

export function placementError(
  candidate: Building,
  plan: Plan,
  catalog: Catalog,
  data: MapData
): string | null {
  const existing = plan.buildings.map(legacyBuilding);
  const building = legacyBuilding(candidate);
  const limit = catalog.buildings[candidate.kind]?.limit ?? 0;
  if (
    plan.buildings.filter((b) => b.kind === candidate.kind && b.allianceId === candidate.allianceId)
      .length >= limit
  )
    return "This alliance has reached the building limit.";
  const radius = buildingRules[building.kind].baseClearance;
  if (
    candidate.x - radius < 0 ||
    candidate.y - radius < 0 ||
    candidate.x + radius > catalog.nativeMapSize ||
    candidate.y + radius > catalog.nativeMapSize
  )
    return "Place the building inside the playable map.";
  if (isProvinceRestricted(data.province, building.kind, candidate.x, candidate.y))
    return "This province does not allow that building.";
  if (plannedBuildingCollision(building, existing))
    return "Another building occupies this position.";
  if (boundaryCollision(candidate.x, candidate.y, radius, data.definitions, data.instances))
    return "The building overlaps forbidden terrain.";
  const structures = mapStructures(catalog, data);
  if (mapStructureCollision(building, structures)) return "The building overlaps a map structure.";
  const ownership = buildTerritoryOwnership(existing, structures);
  if (!isConnectedToAlliance(building, ownership))
    return "Connect flags to this alliance’s territory. Start with a fortress.";
  if (!hasRequiredTerritoryAvailability(building, ownership))
    return "Too much of this footprint belongs to another alliance.";
  return null;
}

export function territorySummary(plan: Plan, catalog: Catalog, data: MapData, allianceId: string) {
  const buildings = plan.buildings.map(legacyBuilding);
  const ownership = buildTerritoryOwnership(buildings, mapStructures(catalog, data));
  const covered = countCoveredResources(ownership, data.resources, allianceId);
  const production = Object.fromEntries(
    Object.entries(covered).map(([kind, count]) => [
      kind === "coin" ? "gold" : kind,
      count * (catalog.resourceProductionPerHour[kind === "coin" ? "gold" : kind] ?? 0),
    ])
  );
  const schedule: BuildingCostSchedule = {};
  for (const [kind, tiers] of Object.entries(catalog.costs))
    schedule[legacyKinds[kind as BuildingKind]] = tiers;
  return {
    ownership,
    covered,
    production,
    entries: buildingCostBreakdown(buildings, schedule, allianceId),
    costs: calculateCostTotals(buildings, schedule, allianceId),
  };
}

/** Reuse production territory rules with the v2 catalog's verified client footprints. */
export function mapStructures(catalog: Catalog, data: MapData): TerritoryStructure[] {
  return data.sites.flatMap((site, index) => {
    if (site.id.startsWith("canyons:")) return [];
    const rule =
      site.kind === "bastion"
        ? {
            collision: { shape: "territory-square" as const, radiusInCells: 1 },
            territoryRadiusInCells: 1,
            teleportRadiusInCells: null,
            claimable: false,
          }
        : catalog.structureRules?.[String(site.strongholdType)];
    if (!rule) return [];
    return [
      {
        ...rule,
        teleportRadiusInCells: rule.teleportRadiusInCells ?? null,
        id: index + 1,
        strongholdType: site.strongholdType ?? 0,
        kind: site.kind as TerritoryStructure["kind"],
        x: site.x,
        y: site.y,
        label: site.label ?? "Bastion",
      },
    ];
  });
}
