import type {
  TerritoryMeshDefinition,
  TerritoryMeshInstance,
  TerritoryResourcePoint,
  TerritoryStructure,
} from "@/autogenerated/container/rokbattles_container";
import type { Alliance, BuildingCostTier, ProvinceRestrictionGrid } from "@/lib/territory/types";

export type Mode = "territory" | "baulur";
export type Season = "preparation" | "season-1" | "season-2" | "season-3" | "conquest";
export type Point = [number, number];
export type BuildingKind = "flag" | "center-fortress" | "fortress" | "horse";
export type AnnotationKind = "line" | "arrow" | "circle" | "text" | "marker";
export type Tool = "select" | AnnotationKind | BuildingKind;
export type MapSummary = {
  map: string;
  name: string;
  season: Season;
  order: number;
  categories: string[];
  overviewUrl: string;
};
export type Catalog = Omit<MapSummary, "overviewUrl"> & {
  schemaVersion: 2;
  bounds: [number, number, number, number];
  pixelSize: [number, number];
  assets: Record<string, { sha256: string; bytes: number }>;
  structureIcons: Record<string, string>;
  structureRules: Record<
    string,
    Pick<
      TerritoryStructure,
      "collision" | "territoryRadiusInCells" | "teleportRadiusInCells" | "claimable"
    >
  >;
  buildingIcons: Record<string, string>;
  siteIcons: Record<string, string>;
  buildings: Partial<Record<BuildingKind, { limit: number }>>;
  costs: Partial<Record<BuildingKind, BuildingCostTier[]>>;
  resourceProductionPerHour: Record<string, number>;
  ruleset: "home" | "lost-land";
  nativeMapSize: number;
};
export type Annotation = {
  id: string;
  kind: AnnotationKind;
  points: Point[];
  color: string;
  width: number;
  text?: string;
};
export type Building = { id: string; kind: BuildingKind; allianceId: string; x: number; y: number };
export type Route = {
  id: string;
  name: string;
  color: string;
  commander: string;
  siteIds: string[];
  startSiteId?: string;
  passes: { siteId: string; allianceId: string }[];
};
export type Plan = {
  version: 2;
  map: string;
  mode: Mode;
  alliances: Alliance[];
  annotations: Annotation[];
  buildings: Building[];
  routes: Route[];
};
export type Site = {
  id: string;
  kind: string;
  x: number;
  y: number;
  label?: string;
  level?: number;
  strongholdType?: number;
  subType?: number;
};
export type MapData = {
  sites: Site[];
  landmarks: Site[];
  resources: TerritoryResourcePoint[];
  definitions: TerritoryMeshDefinition[];
  instances: TerritoryMeshInstance[];
  province: ProvinceRestrictionGrid | null;
  forbiddenBytes: Uint8Array;
};
export type RouteLeg = {
  routeId: string;
  from: string;
  to: string;
  path: Point[] | null;
  start: Point | null;
  end: Point | null;
};
export const PALETTE = [
  "#FF0000",
  "#FF8A00",
  "#FFFC00",
  "#00FF5A",
  "#00DEFF",
  "#0084FF",
  "#B400FF",
  "#FF4DBE",
];
export const API = "/proxy/v2/global/territory-planner";
export const CDN = "https://cdn.rokbattles.com/game/territory";
export const SPRITES = "https://cdn.rokbattles.com/game/sprites";
export const SEASONS: [Season, string][] = [
  ["preparation", "Preparation Season"],
  ["season-1", "Season 1"],
  ["season-2", "Season 2"],
  ["season-3", "Season 3"],
  ["conquest", "Season of Expedition / Conquest"],
];
export function newPlan(map: string, mode: Mode): Plan {
  return {
    version: 2,
    map,
    mode,
    alliances: [{ id: "alliance-1", name: "ROKB", color: PALETTE[4] }],
    annotations: [],
    buildings: [],
    routes: [],
  };
}
