"use client";

import lootData from "@/autogenerated/loot.json";
import { defaultLocale } from "@/i18n/config";
import { resolveDatasetLocale } from "@/i18n/dataset-locale";

const lootMap = lootData.loot;
const lootOrder = new Map<string, number>();
let lootOrderIndex = 0;

for (const [typeId, entries] of Object.entries(lootMap)) {
  for (const subTypeId of Object.keys(entries)) {
    lootOrder.set(`${typeId}:${subTypeId}`, lootOrderIndex);
    lootOrderIndex += 1;
  }
}

type LootTypeKey = keyof typeof lootMap;
type LootEntry = (typeof lootMap)[LootTypeKey];
type LootSubTypeKey = keyof LootEntry;
type LootLocale = keyof LootEntry[LootSubTypeKey]["name"];

export function getLootName(
  typeId: number | null | undefined,
  subTypeId: number | null | undefined,
  locale?: string
) {
  if (typeof typeId !== "number" || !Number.isFinite(typeId)) {
    return undefined;
  }

  if (typeof subTypeId !== "number" || !Number.isFinite(subTypeId)) {
    return undefined;
  }

  const typeEntry = lootMap[String(typeId) as LootTypeKey];
  if (!typeEntry) {
    return undefined;
  }

  const loot = typeEntry[String(subTypeId) as LootSubTypeKey];
  if (!loot) {
    return undefined;
  }

  const requestedLocale = resolveDatasetLocale(locale);
  return (
    // @ts-expect-error
    (loot.name as Record<string, string | undefined>)[requestedLocale] ??
    // @ts-expect-error
    loot.name[defaultLocale as LootLocale]
  );
}

export function getLootOrder(
  typeId: number | null | undefined,
  subTypeId: number | null | undefined
) {
  if (typeof typeId !== "number" || !Number.isFinite(typeId)) {
    return undefined;
  }

  if (typeof subTypeId !== "number" || !Number.isFinite(subTypeId)) {
    return undefined;
  }

  return lootOrder.get(`${typeId}:${subTypeId}`);
}
