[package]
name = "rokbattles-desktop"
description = "A community-driven platform for sharing battle reports and surfacing actionable trends in Rise of Kingdoms."
authors = ["Sylke Technologies, LLC"]
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tauri = { workspace = true, features = ["tray-icon"] }
tauri-plugin-opener = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri-plugin-dialog = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
reqwest = { workspace = true, features = ["json", "multipart", "rustls-tls-native-roots"] }
rokbattles-mail-decoder = { path = "../../common/rokbattles-mail-decoder" }
rokbattles-mail-registry = { path = "../../common/rokbattles-mail-registry" }
tauri-plugin-updater = { workspace = true }
notify = { workspace = true }

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
tauri-plugin-autostart = { workspace = true }
tauri-plugin-single-instance = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[lib]
# The `_lib` suffix keeps the library name from conflicting with the binary
# on Windows. See https://github.com/rust-lang/cargo/issues/8519.
name = "rokbattles_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
doctest = false

[lints]
workspace = true
