"use client";

import { useEffect, useMemo, useState } from "react";
import equipmentData from "@/autogenerated/equipment.json";
import ParticipantCell from "@/components/reports/ParticipantCell";
import {
  DescriptionDetails,
  DescriptionList,
  DescriptionTerm,
} from "@/components/ui/DescriptionList";
import { Heading, Subheading } from "@/components/ui/Heading";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/Table";
import { Text } from "@/components/ui/Text";

type AccessoryPairCount = {
  ids: [number, number];
  count: number;
};

type AccessoryCount = {
  id: number;
  count: number;
};

type PairingSnapshot = {
  primaryCommanderId: number;
  secondaryCommanderId: number;
  reportCount: number;
  accessorySampleCount: number;
  accessoryPairs: AccessoryPairCount[];
  accessories: AccessoryCount[];
};

type CategorySnapshot = {
  totalReports: number;
  pairings: PairingSnapshot[];
};

type TrendSnapshot = {
  trendId: string;
  generatedAt?: string;
  period?: {
    label?: string;
    startMs?: number;
    endMs?: number;
  };
  minReportCount?: number;
  categories?: {
    field?: CategorySnapshot;
    rally?: CategorySnapshot;
    garrison?: CategorySnapshot;
  };
};

type CategoryKey = "field" | "rally" | "garrison";

const DEFAULT_LOCALE = "en";

const equipmentMap = equipmentData.equipment.item as Record<
  string,
  { name: Record<string, string | undefined> }
>;

const CATEGORY_META: Record<CategoryKey, { title: string }> = {
  field: {
    title: "Field Reports",
  },
  rally: {
    title: "Rally Reports",
  },
  garrison: {
    title: "Garrison Reports",
  },
};

function resolveEquipmentName(id: number) {
  if (!Number.isFinite(id) || id <= 0) {
    return "Unknown";
  }
  const equipment = equipmentMap[String(id)];
  return (
    equipment?.name?.[DEFAULT_LOCALE] ??
    equipment?.name?.[Object.keys(equipment?.name ?? {})[0] ?? ""] ??
    String(id)
  );
}

function formatDate(value?: string) {
  if (!value) {
    return "Unknown";
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }
  return parsed.toLocaleString();
}

function AccessoryPairLabel({ pair }: { pair?: AccessoryPairCount }) {
  if (!pair) {
    return <Text className="text-xs text-zinc-500">No accessory pairs recorded.</Text>;
  }

  const [firstId, secondId] = pair.ids;
  return (
    <div className="text-sm text-zinc-950 dark:text-white">
      {resolveEquipmentName(firstId)} <span className="text-zinc-600 dark:text-zinc-400">and</span>{" "}
      {resolveEquipmentName(secondId)}
    </div>
  );
}

function PairingRow({
  pairing,
  categoryKey,
  index,
}: {
  pairing: PairingSnapshot;
  categoryKey: CategoryKey;
  index: number;
}) {
  const topPair = pairing.accessoryPairs[0];
  const pairingLink = `/trends/pairings/${categoryKey}/${pairing.primaryCommanderId}/${pairing.secondaryCommanderId}`;

  return (
    <TableRow href={pairingLink}>
      <TableCell className="text-right font-mono text-zinc-500">{index}</TableCell>
      <TableCell>
        <ParticipantCell
          primaryId={pairing.primaryCommanderId}
          secondaryId={pairing.secondaryCommanderId}
        />
      </TableCell>
      <TableCell>
        <AccessoryPairLabel pair={topPair} />
      </TableCell>
      <TableCell className="text-right font-mono text-zinc-950 dark:text-white">
        {pairing.reportCount.toLocaleString()}
      </TableCell>
    </TableRow>
  );
}

export default function PairingTrendsContent() {
  const [snapshot, setSnapshot] = useState<TrendSnapshot | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;

    const load = async () => {
      try {
        const response = await fetch("/api/v2/trends/pairing-accessories", {
          cache: "no-store",
        });
        if (!response.ok) {
          throw new Error(`Failed to load trends (${response.status})`);
        }
        const data = (await response.json()) as TrendSnapshot;
        if (active) {
          setSnapshot(data);
          setError(null);
        }
      } catch (err) {
        if (active) {
          setError(err instanceof Error ? err.message : "Failed to load trends");
        }
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    };

    load();
    return () => {
      active = false;
    };
  }, []);

  const categories = useMemo(() => {
    const categoryData = snapshot?.categories;
    if (!categoryData) {
      return [] as Array<[CategoryKey, CategorySnapshot]>;
    }
    const order: CategoryKey[] = ["field", "rally", "garrison"];
    return order
      .map((key) => {
        const category = categoryData[key];
        return category ? ([key, category] as [CategoryKey, CategorySnapshot]) : null;
      })
      .filter((entry): entry is [CategoryKey, CategorySnapshot] => Boolean(entry));
  }, [snapshot?.categories]);

  if (loading) {
    return <Text className="mt-6 text-sm text-zinc-500">Loading pairing trends...</Text>;
  }

  if (error) {
    return <Text className="mt-6 text-sm text-rose-600 dark:text-rose-400">{error}</Text>;
  }

  if (!snapshot) {
    return <Text className="mt-6 text-sm text-zinc-500">No trend snapshot found.</Text>;
  }

  return (
    <div className="mt-8 space-y-10">
      <div className="space-y-3">
        <Heading>Trends Overview</Heading>
        <DescriptionList>
          <DescriptionTerm>Period</DescriptionTerm>
          <DescriptionDetails>{snapshot.period?.label ?? "2025 Q4"}</DescriptionDetails>
          <DescriptionTerm>Minimum reports per pairing</DescriptionTerm>
          <DescriptionDetails>
            {snapshot.minReportCount?.toLocaleString() ?? "5,000"}
          </DescriptionDetails>
          <DescriptionTerm>Generated</DescriptionTerm>
          <DescriptionDetails>{formatDate(snapshot.generatedAt)}</DescriptionDetails>
        </DescriptionList>
      </div>

      {categories.map(([key, category]) => {
        const meta = CATEGORY_META[key];
        const pairings = category?.pairings ?? [];

        return (
          <section key={key} className="space-y-4">
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <div>
                <Subheading>{meta.title}</Subheading>
                <Text className="mt-1 text-sm text-zinc-500">
                  {pairings.length.toLocaleString()} Pairings in{" "}
                  {category.totalReports.toLocaleString()} Reports
                </Text>
              </div>
            </div>

            <Table dense className="[--gutter:--spacing(4)] lg:[--gutter:--spacing(6)]">
              <TableHead>
                <TableRow>
                  <TableHeader className="text-right">#</TableHeader>
                  <TableHeader>Pairing</TableHeader>
                  <TableHeader>Top accessory</TableHeader>
                  <TableHeader className="text-right">Reports</TableHeader>
                </TableRow>
              </TableHead>
              <TableBody>
                {pairings.length > 0 ? (
                  pairings.map((pairing, index) => (
                    <PairingRow
                      key={`${pairing.primaryCommanderId}:${pairing.secondaryCommanderId}`}
                      pairing={pairing}
                      categoryKey={key}
                      index={index + 1}
                    />
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={4}>
                      <Text className="text-sm text-zinc-500">
                        No pairings met the threshold for this category.
                      </Text>
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </section>
        );
      })}
    </div>
  );
}
