[package]
name = "rokbattles-ingress"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "json", "multipart", "tokio", "tracing"] }
bytes = { workspace = true }
dotenvy = { workspace = true }
flate2 = { workspace = true, features = ["zlib"] }
rokbattles-mail-decoder = { path = "../../common/rokbattles-mail-decoder" }
rokbattles-mail-registry = { path = "../../common/rokbattles-mail-registry" }
rokbattles-mail-reconstructor = { path = "../../common/rokbattles-mail-reconstructor" }
mongodb = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zstd = { workspace = true }
sentry = { workspace = true, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls"] }

[target.'cfg(all(target_os = "linux", target_env = "musl"))'.dependencies]
mimalloc = { workspace = true, features = ["secure"] }
