import type { Document } from "mongodb";
import { ImageResponse } from "next/og";
import commandersData from "@/autogenerated/commanders.json";
import client from "@/lib/mongo";
import type { RawBattleResults, RawOverview, RawReportPayload } from "@/lib/types/rawReport";

export const contentType = "image/png";

export const size = {
  width: 1200,
  height: 630,
};

type CommanderIdKey = keyof typeof commandersData.commanders;

function getCommanderName(id: number) {
  if (!Number.isFinite(id)) {
    return undefined;
  }

  const commander = commandersData.commanders[String(id) as CommanderIdKey];
  if (!commander) {
    return undefined;
  }

  return commander.name.en;
}

function formatInteger(value: number | null | undefined, suffix: string) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return `N/A${suffix}`;
  }
  return `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value)}${suffix}`;
}

function hasOverviewData(overview: RawOverview | null | undefined) {
  if (!overview) {
    return false;
  }
  const keys: (keyof RawOverview)[] = [
    "max",
    "enemy_max",
    "death",
    "enemy_death",
    "kill_score",
    "enemy_kill_score",
  ];
  return keys.some((key) => overview[key] != null);
}

function extractSummary(payload: RawReportPayload) {
  const overview = payload.overview;
  if (hasOverviewData(overview)) {
    return {
      selfUnits: overview?.max,
      selfKillPoints: overview?.kill_score,
      selfDeaths: overview?.death,
      enemyUnits: overview?.enemy_max,
      enemyKillPoints: overview?.enemy_kill_score,
      enemyDeaths: overview?.enemy_death,
    };
  }

  const battleResults = payload.battle_results as RawBattleResults | null | undefined;
  return {
    selfUnits: battleResults?.max,
    selfKillPoints: battleResults?.kill_score,
    selfDeaths: battleResults?.death,
    enemyUnits: battleResults?.enemy_max,
    enemyKillPoints: battleResults?.enemy_kill_score,
    enemyDeaths: battleResults?.enemy_death,
  };
}

function toPlainObject(source: unknown): Record<string, unknown> {
  if (!source || typeof source !== "object") {
    return {};
  }

  const serialized = JSON.stringify(source, (_, value) => {
    if (
      value &&
      typeof value === "object" &&
      "$numberLong" in (value as Record<string, unknown>) &&
      typeof (value as Record<string, unknown>).$numberLong === "string"
    ) {
      const numericValue = Number((value as { $numberLong: string }).$numberLong);
      return Number.isFinite(numericValue)
        ? numericValue
        : (value as { $numberLong: string }).$numberLong;
    }
    return value;
  });

  return JSON.parse(serialized) as Record<string, unknown>;
}

export default async function Image({ params }: { params: Promise<{ hash?: string }> }) {
  const { hash } = await params;

  try {
    const mongo = await client.connect();
    const db = mongo.db();

    const matchPipeline: Document = {
      "metadata.parentHash": hash ?? "",
      "report.enemy.player_id": { $nin: [-2, 0] },
    };

    const documents = await db
      .collection("battleReports")
      .aggregate(
        [
          { $match: matchPipeline },
          {
            $project: {
              _id: 0,
              startDate: "$report.metadata.start_date",
              report: "$report",
            },
          },
          { $sort: { startDate: 1 } },
          { $limit: 50 },
        ],
        { allowDiskUse: true }
      )
      .toArray();

    const reports = documents.map((doc) => {
      const startDate = doc.startDate;
      const payload = toPlainObject(doc.report) as unknown as RawReportPayload;
      return { startDate, payload };
    });

    const chosen =
      reports.find((entry) => hasOverviewData(entry.payload.overview)) ?? reports[0] ?? null;

    const payload = chosen?.payload ?? ({} as RawReportPayload);
    const summary = extractSummary(payload);

    const selfPrimaryCommander = getCommanderName(payload.self?.primary_commander?.id) ?? "Unknown";
    const selfSecondaryCommander = getCommanderName(payload.self?.secondary_commander?.id);

    const enemyPrimaryCommander =
      getCommanderName(payload.enemy?.primary_commander?.id) ?? "Unknown";
    const enemySecondaryCommander = getCommanderName(payload.enemy?.secondary_commander?.id);

    const image = new ImageResponse(
      <div tw="w-full h-full flex flex-col bg-zinc-900 text-white">
        <div tw="w-full pt-14 px-16 flex items-center justify-start">
          <div tw="text-5xl font-semibold tracking-tight">Battle Report</div>
        </div>
        <div tw="flex-1 w-full flex items-start justify-between px-16 pt-14">
          <div tw="flex flex-col max-w-[520px]">
            <div tw="text-6xl font-semibold leading-none">{selfPrimaryCommander}</div>
            {selfSecondaryCommander ? (
              <div tw="mt-3 text-4xl font-normal text-zinc-200 leading-none">
                {selfSecondaryCommander}
              </div>
            ) : null}
            <div tw="mt-10 flex flex-col text-3xl text-zinc-200">
              <div>{formatInteger(summary.selfUnits, " Units")}</div>
              <div tw="mt-3">{formatInteger(summary.selfKillPoints, " Kill Points")}</div>
              <div tw="mt-3">{formatInteger(summary.selfDeaths, " Deaths")}</div>
            </div>
          </div>
          <div tw="flex flex-col max-w-[520px] items-end text-right">
            <div tw="text-6xl font-semibold leading-none">{enemyPrimaryCommander}</div>
            {enemySecondaryCommander ? (
              <div tw="mt-3 text-4xl font-normal text-zinc-200 leading-none">
                {enemySecondaryCommander}
              </div>
            ) : null}
            <div tw="mt-10 flex flex-col text-3xl text-zinc-200 items-end">
              <div>{formatInteger(summary.enemyUnits, " Units")}</div>
              <div tw="mt-3">{formatInteger(summary.enemyKillPoints, " Kill Points")}</div>
              <div tw="mt-3">{formatInteger(summary.enemyDeaths, " Deaths")}</div>
            </div>
          </div>
        </div>
        <div tw="w-full px-16 pb-12 flex items-end">
          <div tw="text-zinc-500 text-2xl">Powered by ROK Battles</div>
        </div>
      </div>,
      size
    );

    image.headers.set("Cache-Control", "public, max-age=604800, immutable");
    return image;
  } catch (error) {
    console.error("Failed to generate report OpenGraph image", error);

    const image = new ImageResponse(
      <div
        tw="w-full h-full flex flex-col items-center justify-center text-white"
        style={{ backgroundColor: "#09090b" }}
      >
        <div tw="text-5xl font-semibold tracking-tight">Battle Report</div>
        <div tw="mt-6 text-3xl text-zinc-300">Failed to load report</div>
      </div>,
      size
    );

    image.headers.set("Cache-Control", "no-store");
    return image;
  }
}
