[package]
name = "rokbattles-mail-reconstructor"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
doctest = false

[dependencies]
base64 = { workspace = true }
flate2 = { workspace = true, features = ["zlib-rs"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
rokbattles-mail-codec = { path = "../rokbattles-mail-codec", features = ["write"] }
rokbattles-mail-registry = { path = "../rokbattles-mail-registry" }

[dev-dependencies]
rokbattles-mail-codec = { path = "../rokbattles-mail-codec", features = ["read"] }
rokbattles-mail-processor-system-barbarianfort = { path = "../rokbattles-mail-processor-system-barbarianfort" }

[lints]
workspace = true
