#![forbid(unsafe_code)]

//! TypeScript package generation from the concrete Rust mail types.

use std::{
    any::TypeId,
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use rokbattles_codegen_mail_types::{
    allianceaoobattleinfo::AllianceAooBattleInfo,
    allianceaoobattleresults::AllianceAooBattleResults,
    allianceaooindividualresults::AllianceAooIndividualResults,
    allianceaooregistration::AllianceAooRegistration, barcanyonkillboss::BarCanyonKillBoss,
    battle::Battle, duelbattle2::DuelBattle2, eventmemberlootreport::EventMemberLootReport,
    rss::Rss, scoutreport::ScoutReport, systembarbarianfort::SystemBarbarianFort,
    systemkahartreasure::SystemKaharTreasure,
};
use ts_rs::{Config, TS, TypeVisitor};

const PACKAGE_JSON: &str = r#"{
  "name": "@rokbattles/types",
  "version": "1.6.1",
  "private": true,
  "type": "module",
  "exports": {
    "./mail/*": "./src/mail/*.ts"
  }
}
"#;

const GENERATED_HEADER: &str = "// Generated by rokbattles-codegen. Do not edit.\n\n";

/// Generates the `@rokbattles/types` package at `output_dir`.
///
/// # Errors
///
/// Returns an error when the output directory cannot be read or written.
pub fn generate(output_dir: &Path) -> Result<()> {
    let mail_dir = output_dir.join("src/mail");
    fs::create_dir_all(&mail_dir)
        .with_context(|| format!("failed to create {}", mail_dir.display()))?;

    let config = Config::default().with_large_int("number");
    let modules = [
        ("allianceaoobattleinfo.ts", render_module::<AllianceAooBattleInfo>(&config)?),
        ("allianceaoobattleresults.ts", render_module::<AllianceAooBattleResults>(&config)?),
        (
            "allianceaooindividualresults.ts",
            render_module::<AllianceAooIndividualResults>(&config)?,
        ),
        ("allianceaooregistration.ts", render_module::<AllianceAooRegistration>(&config)?),
        ("barcanyonkillboss.ts", render_module::<BarCanyonKillBoss>(&config)?),
        ("battle.ts", render_module::<Battle>(&config)?),
        ("duelbattle2.ts", render_module::<DuelBattle2>(&config)?),
        ("eventmemberlootreport.ts", render_module::<EventMemberLootReport>(&config)?),
        ("rss.ts", render_module::<Rss>(&config)?),
        ("scoutreport.ts", render_module::<ScoutReport>(&config)?),
        ("systembarbarianfort.ts", render_module::<SystemBarbarianFort>(&config)?),
        ("systemkahartreasure.ts", render_module::<SystemKaharTreasure>(&config)?),
    ];

    remove_stale_modules(&mail_dir, modules.iter().map(|(name, _)| *name))?;
    write_if_changed(&output_dir.join("package.json"), PACKAGE_JSON)?;
    for (name, contents) in modules {
        write_if_changed(&mail_dir.join(name), &contents)?;
    }

    Ok(())
}

fn render_module<T: TS + 'static>(config: &Config) -> Result<String> {
    let mut collector = DeclarationCollector::new(config);
    collector.visit::<T>();

    if let Some(type_name) = collector.invalid_declaration {
        anyhow::bail!("failed to format TypeScript declaration for {type_name}");
    }

    let mut output = String::from(GENERATED_HEADER);
    for declaration in collector.declarations.into_values() {
        output.push_str(&declaration);
        output.push('\n');
    }
    Ok(output)
}

struct DeclarationCollector<'a> {
    config: &'a Config,
    seen: BTreeSet<TypeId>,
    declarations: BTreeMap<String, String>,
    invalid_declaration: Option<&'static str>,
}

impl<'a> DeclarationCollector<'a> {
    fn new(config: &'a Config) -> Self {
        Self {
            config,
            seen: BTreeSet::new(),
            declarations: BTreeMap::new(),
            invalid_declaration: None,
        }
    }
}

impl TypeVisitor for DeclarationCollector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if !self.seen.insert(TypeId::of::<T>()) {
            return;
        }

        T::visit_dependencies(self);
        if T::output_path().is_some() && self.invalid_declaration.is_none() {
            let declaration = T::decl(self.config);
            if let Some(formatted) = format_declaration(&declaration) {
                self.declarations.insert(T::ident(self.config), formatted);
            } else {
                self.invalid_declaration = Some(std::any::type_name::<T>());
            }
        }
    }
}

fn format_declaration(declaration: &str) -> Option<String> {
    let open = declaration.find('{')?;
    let close = declaration.rfind('}')?;
    let prefix = declaration.get(..open)?.trim_end();
    let fields = declaration.get(open + 1..close)?;

    let mut formatted = format!("export {prefix} {{\n");
    for field in fields.split(',').map(str::trim).filter(|field| !field.is_empty()) {
        formatted.push_str("  ");
        formatted.push_str(field);
        formatted.push_str(";\n");
    }
    formatted.push_str("};");
    Some(formatted)
}

fn remove_stale_modules<'a>(
    mail_dir: &Path,
    expected_names: impl Iterator<Item = &'a str>,
) -> Result<()> {
    let expected: BTreeSet<&str> = expected_names.collect();
    for entry in
        fs::read_dir(mail_dir).with_context(|| format!("failed to read {}", mail_dir.display()))?
    {
        let entry = entry.with_context(|| format!("failed to read {}", mail_dir.display()))?;
        let path = entry.path();
        let is_typescript = path.extension().is_some_and(|extension| extension == "ts");
        let is_expected = path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| expected.contains(name));
        if is_typescript && !is_expected {
            fs::remove_file(&path)
                .with_context(|| format!("failed to remove stale module {}", path.display()))?;
        }
    }
    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<()> {
    if fs::read_to_string(path).is_ok_and(|existing| existing == contents) {
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}

/// Returns the repository-default package output directory.
#[must_use]
pub fn default_output_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../packages/types")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_writes_all_mail_modules_without_a_barrel() {
        let temp = tempfile::tempdir().expect("temporary directory");
        let output = temp.path().join("types");

        generate(&output).expect("generate package");

        let files = fs::read_dir(output.join("src/mail"))
            .expect("read mail modules")
            .collect::<Result<Vec<_>, _>>()
            .expect("read directory entries");
        assert_eq!(files.len(), 12);
    }

    #[test]
    fn generate_exposes_only_the_mail_wildcard() {
        let temp = tempfile::tempdir().expect("temporary directory");
        let output = temp.path().join("types");

        generate(&output).expect("generate package");

        let package_json = fs::read_to_string(output.join("package.json")).expect("package json");
        assert_eq!(package_json, PACKAGE_JSON);
    }

    #[test]
    fn generated_battle_module_exports_the_concrete_type() {
        let config = Config::default().with_large_int("number");

        let module = render_module::<Battle>(&config).expect("render battle module");

        assert!(module.contains("export type Battle ="), "generated module was: {module}");
    }

    #[test]
    fn generate_removes_stale_typescript_modules() {
        let temp = tempfile::tempdir().expect("temporary directory");
        let output = temp.path().join("types");
        let mail_dir = output.join("src/mail");
        fs::create_dir_all(&mail_dir).expect("mail directory");
        fs::write(mail_dir.join("index.ts"), "export {};\n").expect("stale barrel");

        generate(&output).expect("generate package");

        assert!(!mail_dir.join("index.ts").exists());
    }
}
